// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flux/fnft/v1beta1/nft.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NFTStatus int32

const (
	NFTStatus_ISO    NFTStatus = 0
	NFTStatus_Failed NFTStatus = 1
	NFTStatus_Active NFTStatus = 2
)

var NFTStatus_name = map[int32]string{
	0: "ISO",
	1: "Failed",
	2: "Active",
}

var NFTStatus_value = map[string]int32{
	"ISO":    0,
	"Failed": 1,
	"Active": 2,
}

func (x NFTStatus) String() string {
	return proto.EnumName(NFTStatus_name, int32(x))
}

func (NFTStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_293fbd88035f93df, []int{0}
}

// Class defines the class of the nft type.
type Class struct {
	// id defines the unique identifier of the NFT classification, similar to the
	// contract address of ERC721
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name defines the human-readable name of the NFT classification. Optional
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// symbol is an abbreviated name for nft classification. Optional
	Symbol string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// description is a brief description of nft classification. Optional
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// url for the class metadata stored off chain. It can define schema for Class
	// and NFT `Data` attributes. Optional
	Url string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	// data is the app specific metadata of the NFT class. Optional
	Data *types.Any `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Class) Reset()         { *m = Class{} }
func (m *Class) String() string { return proto.CompactTextString(m) }
func (*Class) ProtoMessage()    {}
func (*Class) Descriptor() ([]byte, []int) {
	return fileDescriptor_293fbd88035f93df, []int{0}
}
func (m *Class) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Class) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Class.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Class) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Class.Merge(m, src)
}
func (m *Class) XXX_Size() int {
	return m.Size()
}
func (m *Class) XXX_DiscardUnknown() {
	xxx_messageInfo_Class.DiscardUnknown(m)
}

var xxx_messageInfo_Class proto.InternalMessageInfo

func (m *Class) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Class) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Class) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Class) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Class) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Class) GetData() *types.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

// NFT defines the NFT.
type NFT struct {
	// class_id associated with the NFT, similar to the contract address of ERC721
	ClassId string `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty" bson:"classId"`
	// id is a unique identifier of the NFT
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id"`
	// url for the NFT metadata stored off chain
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty" bson:"url"`
	// supply is shares supply for this nft
	Supply cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=supply,proto3,customtype=cosmossdk.io/math.Int" json:"supply" bson:"supply"`
	// owner equity is the percentage of shares owner will receive via vesting
	OwnerEquityPercent cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=owner_equity_percent,json=ownerEquityPercent,proto3,customtype=cosmossdk.io/math.Int" json:"owner_equity_percent" bson:"ownerEquityPercent"`
	// available shares to purchase within iso period
	AvailableShares cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=available_shares,json=availableShares,proto3,customtype=cosmossdk.io/math.Int" json:"available_shares" bson:"availableShares"`
	// iso price per share
	InitialPrice github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,7,opt,name=initial_price,json=initialPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"initial_price" bson:"initialPrice"`
	// timestamp when iso period is over
	ISOTimestamp      uint64 `protobuf:"varint,8,opt,name=ISO_timestamp,json=ISOTimestamp,proto3" json:"ISO_timestamp,omitempty" bson:"isoTimestamp"`
	ISOSuccessPercent uint64 `protobuf:"varint,9,opt,name=ISO_success_percent,json=ISOSuccessPercent,proto3" json:"ISO_success_percent,omitempty"`
	// sponsorships must use this denom
	AcceptedPaymentDenom string `protobuf:"bytes,10,opt,name=accepted_payment_denom,json=acceptedPaymentDenom,proto3" json:"accepted_payment_denom,omitempty" bson:"acceptedPaymentDenom"`
	// array of sponsorship in this dividend period
	Sponsorships []*Sponsorship `protobuf:"bytes,11,rep,name=sponsorships,proto3" json:"sponsorships,omitempty" bson:"sponsorships"`
	// sponsorship coins will be accumulated in revenue
	Revenue *types1.Coin `protobuf:"bytes,12,opt,name=revenue,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"revenue,omitempty" bson:"revenue"`
	// interval to distribute dividend to users
	DividendInterval uint64 `protobuf:"varint,13,opt,name=dividend_interval,json=dividendInterval,proto3" json:"dividend_interval,omitempty" bson:"dividendInterval"`
	// last dividend timestamp
	LastDividendTimestamp uint64 `protobuf:"varint,14,opt,name=last_dividend_timestamp,json=lastDividendTimestamp,proto3" json:"last_dividend_timestamp,omitempty" bson:"lastDividendTimestamp"`
	// nft owner
	Owner string `protobuf:"bytes,15,opt,name=owner,proto3" json:"owner,omitempty" bson:"owner"`
	// indicate if nft passes iso or not
	Status NFTStatus `protobuf:"varint,16,opt,name=status,proto3,enum=flux.fnft.v1beta1.NFTStatus" json:"status,omitempty" bson:"active"`
	// data is an app specific data of the NFT. Optional
	Data *types.Any `protobuf:"bytes,17,opt,name=data,proto3" json:"data,omitempty" bson:"data"`
}

func (m *NFT) Reset()         { *m = NFT{} }
func (m *NFT) String() string { return proto.CompactTextString(m) }
func (*NFT) ProtoMessage()    {}
func (*NFT) Descriptor() ([]byte, []int) {
	return fileDescriptor_293fbd88035f93df, []int{1}
}
func (m *NFT) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NFT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NFT.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NFT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NFT.Merge(m, src)
}
func (m *NFT) XXX_Size() int {
	return m.Size()
}
func (m *NFT) XXX_DiscardUnknown() {
	xxx_messageInfo_NFT.DiscardUnknown(m)
}

var xxx_messageInfo_NFT proto.InternalMessageInfo

func (m *NFT) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

func (m *NFT) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NFT) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *NFT) GetISOTimestamp() uint64 {
	if m != nil {
		return m.ISOTimestamp
	}
	return 0
}

func (m *NFT) GetISOSuccessPercent() uint64 {
	if m != nil {
		return m.ISOSuccessPercent
	}
	return 0
}

func (m *NFT) GetAcceptedPaymentDenom() string {
	if m != nil {
		return m.AcceptedPaymentDenom
	}
	return ""
}

func (m *NFT) GetSponsorships() []*Sponsorship {
	if m != nil {
		return m.Sponsorships
	}
	return nil
}

func (m *NFT) GetRevenue() *types1.Coin {
	if m != nil {
		return m.Revenue
	}
	return nil
}

func (m *NFT) GetDividendInterval() uint64 {
	if m != nil {
		return m.DividendInterval
	}
	return 0
}

func (m *NFT) GetLastDividendTimestamp() uint64 {
	if m != nil {
		return m.LastDividendTimestamp
	}
	return 0
}

func (m *NFT) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *NFT) GetStatus() NFTStatus {
	if m != nil {
		return m.Status
	}
	return NFTStatus_ISO
}

func (m *NFT) GetData() *types.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type Sponsorship struct {
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Url         string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (m *Sponsorship) Reset()         { *m = Sponsorship{} }
func (m *Sponsorship) String() string { return proto.CompactTextString(m) }
func (*Sponsorship) ProtoMessage()    {}
func (*Sponsorship) Descriptor() ([]byte, []int) {
	return fileDescriptor_293fbd88035f93df, []int{2}
}
func (m *Sponsorship) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sponsorship) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Sponsorship.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Sponsorship) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sponsorship.Merge(m, src)
}
func (m *Sponsorship) XXX_Size() int {
	return m.Size()
}
func (m *Sponsorship) XXX_DiscardUnknown() {
	xxx_messageInfo_Sponsorship.DiscardUnknown(m)
}

var xxx_messageInfo_Sponsorship proto.InternalMessageInfo

func (m *Sponsorship) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Sponsorship) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Holder struct {
	ClassId string                `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty" bson:"classId"`
	Id      string                `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id"`
	Address string                `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty" bson:"address"`
	Shares  cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=shares,proto3,customtype=cosmossdk.io/math.Int" json:"shares" bson:"shares"`
}

func (m *Holder) Reset()         { *m = Holder{} }
func (m *Holder) String() string { return proto.CompactTextString(m) }
func (*Holder) ProtoMessage()    {}
func (*Holder) Descriptor() ([]byte, []int) {
	return fileDescriptor_293fbd88035f93df, []int{3}
}
func (m *Holder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Holder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Holder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Holder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Holder.Merge(m, src)
}
func (m *Holder) XXX_Size() int {
	return m.Size()
}
func (m *Holder) XXX_DiscardUnknown() {
	xxx_messageInfo_Holder.DiscardUnknown(m)
}

var xxx_messageInfo_Holder proto.InternalMessageInfo

func (m *Holder) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

func (m *Holder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Holder) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterEnum("flux.fnft.v1beta1.NFTStatus", NFTStatus_name, NFTStatus_value)
	proto.RegisterType((*Class)(nil), "flux.fnft.v1beta1.Class")
	proto.RegisterType((*NFT)(nil), "flux.fnft.v1beta1.NFT")
	proto.RegisterType((*Sponsorship)(nil), "flux.fnft.v1beta1.Sponsorship")
	proto.RegisterType((*Holder)(nil), "flux.fnft.v1beta1.Holder")
}

func init() { proto.RegisterFile("flux/fnft/v1beta1/nft.proto", fileDescriptor_293fbd88035f93df) }

var fileDescriptor_293fbd88035f93df = []byte{
	// 990 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xe4, 0x34,
	0x18, 0x6e, 0xfa, 0x31, 0xdd, 0x7a, 0xfa, 0x31, 0xf5, 0x76, 0xdb, 0x74, 0xbb, 0x4c, 0x46, 0xb9,
	0x30, 0x5a, 0xd1, 0x44, 0x5b, 0x84, 0x10, 0x2b, 0x84, 0xd4, 0x6c, 0x19, 0x76, 0x24, 0xd4, 0x56,
	0x99, 0x22, 0x21, 0x38, 0x44, 0x9e, 0xc4, 0x9d, 0x5a, 0x9b, 0xd8, 0x21, 0x76, 0x86, 0x9d, 0x3f,
	0xc0, 0x99, 0x33, 0x37, 0xae, 0x9c, 0xf9, 0x11, 0x3d, 0xae, 0x38, 0x21, 0x0e, 0x01, 0xb5, 0xfc,
	0x82, 0xfc, 0x02, 0x14, 0xdb, 0xf3, 0x41, 0xb7, 0x55, 0x41, 0xda, 0x53, 0xec, 0xf7, 0x79, 0x3f,
	0xfc, 0xbe, 0x8f, 0xfd, 0x04, 0xec, 0x9d, 0xc7, 0xf9, 0x6b, 0xf7, 0x9c, 0x9e, 0x0b, 0x77, 0xf8,
	0xac, 0x8f, 0x05, 0x7a, 0xe6, 0xd2, 0x73, 0xe1, 0xa4, 0x19, 0x13, 0x0c, 0x6e, 0x56, 0xa0, 0x53,
	0x81, 0x8e, 0x06, 0x1f, 0xef, 0x0e, 0x18, 0x1b, 0xc4, 0xd8, 0x95, 0x0e, 0xfd, 0xfc, 0xdc, 0x45,
	0x74, 0xa4, 0xbc, 0x1f, 0x6f, 0x0d, 0xd8, 0x80, 0xc9, 0xa5, 0x5b, 0xad, 0xb4, 0x75, 0x37, 0x64,
	0x3c, 0x61, 0x3c, 0x50, 0x80, 0xda, 0x68, 0xa8, 0xa9, 0x76, 0x6e, 0x1f, 0x71, 0x3c, 0xa9, 0x1e,
	0x32, 0x42, 0x15, 0x6e, 0xff, 0x6c, 0x80, 0xa5, 0x17, 0x31, 0xe2, 0x1c, 0xae, 0x83, 0x79, 0x12,
	0x99, 0x46, 0xcb, 0x68, 0xaf, 0xf8, 0xf3, 0x24, 0x82, 0x10, 0x2c, 0x52, 0x94, 0x60, 0x73, 0x5e,
	0x5a, 0xe4, 0x1a, 0x6e, 0x83, 0x1a, 0x1f, 0x25, 0x7d, 0x16, 0x9b, 0x0b, 0xd2, 0xaa, 0x77, 0xb0,
	0x05, 0xea, 0x11, 0xe6, 0x61, 0x46, 0x52, 0x41, 0x18, 0x35, 0x17, 0x25, 0x38, 0x6b, 0x82, 0x0d,
	0xb0, 0x90, 0x67, 0xb1, 0xb9, 0x24, 0x91, 0x6a, 0x09, 0xdb, 0x60, 0x31, 0x42, 0x02, 0x99, 0xb5,
	0x96, 0xd1, 0xae, 0x1f, 0x6c, 0x39, 0xaa, 0x69, 0x67, 0xdc, 0xb4, 0x73, 0x48, 0x47, 0xbe, 0xf4,
	0xb0, 0x7f, 0x02, 0x60, 0xe1, 0xb8, 0x73, 0x06, 0xf7, 0xc1, 0x83, 0xb0, 0x3a, 0x6a, 0x30, 0x3e,
	0xa7, 0x07, 0xcb, 0xc2, 0x5a, 0xef, 0x73, 0x46, 0x9f, 0xdb, 0x12, 0xe9, 0x46, 0xb6, 0xbf, 0xac,
	0x57, 0xf0, 0x3d, 0xd9, 0x90, 0x3c, 0xbe, 0xb7, 0x56, 0x16, 0xd6, 0x8a, 0x72, 0x24, 0x91, 0x2d,
	0xfb, 0x6b, 0xa9, 0x13, 0xc9, 0x46, 0xbc, 0xf5, 0xb2, 0xb0, 0x80, 0xc2, 0xf3, 0x2c, 0xb6, 0xd5,
	0x09, 0x3b, 0xa0, 0xc6, 0xf3, 0x34, 0x8d, 0x47, 0xaa, 0x21, 0xcf, 0xb9, 0x2c, 0xac, 0xb9, 0x3f,
	0x0a, 0xeb, 0x91, 0x9a, 0x29, 0x8f, 0x5e, 0x39, 0x84, 0xb9, 0x09, 0x12, 0x17, 0x4e, 0x97, 0x8a,
	0xb2, 0xb0, 0xd6, 0x54, 0x06, 0x15, 0x64, 0xfb, 0x3a, 0x1a, 0xc6, 0x60, 0x8b, 0x7d, 0x4f, 0x71,
	0x16, 0xe0, 0xef, 0x72, 0x22, 0x46, 0x41, 0x8a, 0xb3, 0x10, 0x53, 0xa1, 0x86, 0xe1, 0x3d, 0xbf,
	0x2f, 0xeb, 0xae, 0xca, 0x2a, 0x53, 0x7c, 0x2e, 0x33, 0x9c, 0xaa, 0x04, 0xb6, 0x0f, 0xdf, 0x36,
	0xc2, 0x3e, 0x68, 0xa0, 0x21, 0x22, 0x31, 0xea, 0xc7, 0x38, 0xe0, 0x17, 0x28, 0xc3, 0x5c, 0xce,
	0x78, 0xc5, 0xfb, 0xf8, 0xbe, 0x4a, 0xdb, 0xaa, 0xd2, 0x24, 0xbc, 0x27, 0xa3, 0x6d, 0x7f, 0xe3,
	0x86, 0x05, 0xfe, 0x60, 0x80, 0x35, 0x42, 0x89, 0x20, 0x28, 0x0e, 0xd2, 0x8c, 0x84, 0xd8, 0x5c,
	0x96, 0x2c, 0xee, 0x3a, 0xfa, 0xf2, 0x55, 0xd7, 0x6d, 0x7c, 0x9f, 0x9d, 0x17, 0x8c, 0x50, 0xaf,
	0xa3, 0x8b, 0xbf, 0x3f, 0x20, 0xe2, 0x22, 0xef, 0x3b, 0x21, 0x4b, 0xf4, 0x4d, 0xd5, 0x9f, 0x7d,
	0x1e, 0xbd, 0x72, 0xc5, 0x28, 0xc5, 0x5c, 0x06, 0x94, 0x85, 0xf5, 0x50, 0x13, 0xa6, 0x0a, 0x9d,
	0x56, 0x75, 0x6c, 0x7f, 0x75, 0x76, 0x0b, 0x3f, 0x05, 0x6b, 0xdd, 0xde, 0x49, 0x20, 0x48, 0x82,
	0xb9, 0x40, 0x49, 0x6a, 0x3e, 0x68, 0x19, 0xed, 0x45, 0x6f, 0x67, 0x26, 0x9a, 0xb3, 0xb3, 0x31,
	0x6a, 0xfb, 0xab, 0xdd, 0xde, 0xc9, 0x64, 0x0b, 0x1d, 0xf0, 0xb0, 0x8a, 0xe6, 0x79, 0x18, 0x62,
	0xce, 0x27, 0xbc, 0xac, 0x54, 0x39, 0xfc, 0xcd, 0x6e, 0xef, 0xa4, 0xa7, 0x90, 0xf1, 0x68, 0xbf,
	0x02, 0xdb, 0x28, 0x0c, 0x71, 0x2a, 0x70, 0x14, 0xa4, 0x68, 0x94, 0x60, 0x2a, 0x82, 0x08, 0x53,
	0x96, 0x98, 0x40, 0x0e, 0xd8, 0x2a, 0x0b, 0x6b, 0x4f, 0xcf, 0x50, 0xfb, 0x9d, 0x2a, 0xb7, 0xa3,
	0xca, 0xcb, 0xf6, 0xb7, 0x6e, 0x33, 0xc3, 0x6f, 0xc1, 0x2a, 0x4f, 0x19, 0xe5, 0x2c, 0xe3, 0x17,
	0x24, 0xe5, 0x66, 0xbd, 0xb5, 0xd0, 0xae, 0x1f, 0x34, 0x9d, 0xb7, 0x94, 0xc1, 0xe9, 0x4d, 0xdd,
	0x66, 0x7b, 0x9c, 0x8d, 0xb6, 0xfd, 0x7f, 0x25, 0x83, 0x43, 0xb0, 0x9c, 0xe1, 0x21, 0xa6, 0x39,
	0x36, 0x57, 0xef, 0xe3, 0xe8, 0xf0, 0xb2, 0xb0, 0x8c, 0xe9, 0x93, 0xd2, 0x71, 0xf6, 0x2f, 0x7f,
	0xfe, 0x67, 0xd6, 0xfc, 0x71, 0x31, 0xf8, 0x12, 0x6c, 0x46, 0x64, 0x48, 0x22, 0x4c, 0xa3, 0x80,
	0x50, 0x81, 0xb3, 0x21, 0x8a, 0xcd, 0x35, 0xc9, 0xce, 0x5e, 0x59, 0x58, 0x3b, 0xaa, 0xc4, 0xd8,
	0xa5, 0xab, 0x3d, 0x6c, 0xbf, 0x71, 0xd3, 0x04, 0xbf, 0x06, 0x3b, 0x31, 0xe2, 0x22, 0x98, 0xa4,
	0x9b, 0xb2, 0xbd, 0x2e, 0xf3, 0xb5, 0xca, 0xc2, 0x7a, 0xa2, 0xf2, 0x55, 0x8e, 0x47, 0xda, 0x6f,
	0x86, 0xf6, 0x47, 0xb7, 0xda, 0xe1, 0x67, 0x60, 0x49, 0x3e, 0x20, 0x73, 0x43, 0xd2, 0xd7, 0x2e,
	0x0b, 0x6b, 0x75, 0xe6, 0xb1, 0xd9, 0xbf, 0xfd, 0xba, 0xbf, 0xa5, 0x87, 0x75, 0x18, 0x45, 0x19,
	0xe6, 0xbc, 0x27, 0x32, 0x42, 0x07, 0xbe, 0x0a, 0x83, 0x5f, 0x80, 0x1a, 0x17, 0x48, 0xe4, 0xdc,
	0x6c, 0xb4, 0x8c, 0xf6, 0xfa, 0xc1, 0x93, 0x5b, 0x28, 0x3b, 0xee, 0x9c, 0xf5, 0xa4, 0x8f, 0xb7,
	0x39, 0x55, 0x08, 0x14, 0x0a, 0x32, 0xc4, 0x95, 0x42, 0x48, 0x08, 0x7e, 0xa2, 0xb5, 0x70, 0xf3,
	0x6e, 0x2d, 0xf4, 0x36, 0xca, 0xc2, 0xaa, 0xeb, 0xa9, 0x55, 0xaa, 0xa8, 0xc5, 0xf1, 0x10, 0xd4,
	0x67, 0x6e, 0xc5, 0x4d, 0x25, 0x36, 0xee, 0x54, 0xe2, 0xf9, 0x89, 0x12, 0xdb, 0x7f, 0x1b, 0xa0,
	0xf6, 0x92, 0xc5, 0x11, 0xce, 0xde, 0xb1, 0xc4, 0x1e, 0x81, 0x65, 0xa4, 0xe6, 0xa6, 0x65, 0xf6,
	0xe9, 0x34, 0x99, 0x06, 0xee, 0x9e, 0xf1, 0x38, 0x54, 0xca, 0xb0, 0x92, 0xb1, 0xff, 0x29, 0xc3,
	0x5a, 0xbd, 0x74, 0xf4, 0xd3, 0x0f, 0xc0, 0xca, 0x84, 0x0c, 0xb8, 0x0c, 0x16, 0xba, 0xbd, 0x93,
	0xc6, 0x1c, 0x04, 0xa0, 0xd6, 0x41, 0x24, 0xc6, 0x51, 0xc3, 0xa8, 0xd6, 0x87, 0x92, 0x99, 0xc6,
	0xbc, 0x77, 0x72, 0x79, 0xd5, 0x34, 0xde, 0x5c, 0x35, 0x8d, 0xbf, 0xae, 0x9a, 0xc6, 0x8f, 0xd7,
	0xcd, 0xb9, 0x37, 0xd7, 0xcd, 0xb9, 0xdf, 0xaf, 0x9b, 0x73, 0xdf, 0x7c, 0x34, 0xf3, 0x16, 0x3a,
	0x71, 0xfe, 0xfa, 0xb8, 0x73, 0xf6, 0x25, 0xea, 0x73, 0xb7, 0xe2, 0x3e, 0x72, 0xc3, 0x0b, 0x44,
	0xa8, 0x9b, 0xb0, 0x28, 0x8f, 0x31, 0x57, 0x3f, 0x7d, 0xf9, 0x3c, 0xfa, 0x35, 0xc9, 0xe6, 0x87,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x16, 0x47, 0xfc, 0x00, 0x0e, 0x08, 0x00, 0x00,
}

func (m *Class) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Class) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Class) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Data != nil {
		{
			size, err := m.Data.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNft(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintNft(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintNft(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintNft(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintNft(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintNft(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NFT) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NFT) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NFT) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Data != nil {
		{
			size, err := m.Data.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNft(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if m.Status != 0 {
		i = encodeVarintNft(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintNft(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x7a
	}
	if m.LastDividendTimestamp != 0 {
		i = encodeVarintNft(dAtA, i, uint64(m.LastDividendTimestamp))
		i--
		dAtA[i] = 0x70
	}
	if m.DividendInterval != 0 {
		i = encodeVarintNft(dAtA, i, uint64(m.DividendInterval))
		i--
		dAtA[i] = 0x68
	}
	if m.Revenue != nil {
		{
			size, err := m.Revenue.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNft(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	if len(m.Sponsorships) > 0 {
		for iNdEx := len(m.Sponsorships) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sponsorships[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintNft(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.AcceptedPaymentDenom) > 0 {
		i -= len(m.AcceptedPaymentDenom)
		copy(dAtA[i:], m.AcceptedPaymentDenom)
		i = encodeVarintNft(dAtA, i, uint64(len(m.AcceptedPaymentDenom)))
		i--
		dAtA[i] = 0x52
	}
	if m.ISOSuccessPercent != 0 {
		i = encodeVarintNft(dAtA, i, uint64(m.ISOSuccessPercent))
		i--
		dAtA[i] = 0x48
	}
	if m.ISOTimestamp != 0 {
		i = encodeVarintNft(dAtA, i, uint64(m.ISOTimestamp))
		i--
		dAtA[i] = 0x40
	}
	{
		size := m.InitialPrice.Size()
		i -= size
		if _, err := m.InitialPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.AvailableShares.Size()
		i -= size
		if _, err := m.AvailableShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.OwnerEquityPercent.Size()
		i -= size
		if _, err := m.OwnerEquityPercent.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Supply.Size()
		i -= size
		if _, err := m.Supply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintNft(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintNft(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClassId) > 0 {
		i -= len(m.ClassId)
		copy(dAtA[i:], m.ClassId)
		i = encodeVarintNft(dAtA, i, uint64(len(m.ClassId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Sponsorship) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sponsorship) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Sponsorship) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintNft(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintNft(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Holder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Holder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Holder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Shares.Size()
		i -= size
		if _, err := m.Shares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintNft(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintNft(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClassId) > 0 {
		i -= len(m.ClassId)
		copy(dAtA[i:], m.ClassId)
		i = encodeVarintNft(dAtA, i, uint64(len(m.ClassId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintNft(dAtA []byte, offset int, v uint64) int {
	offset -= sovNft(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Class) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	if m.Data != nil {
		l = m.Data.Size()
		n += 1 + l + sovNft(uint64(l))
	}
	return n
}

func (m *NFT) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClassId)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	l = m.Supply.Size()
	n += 1 + l + sovNft(uint64(l))
	l = m.OwnerEquityPercent.Size()
	n += 1 + l + sovNft(uint64(l))
	l = m.AvailableShares.Size()
	n += 1 + l + sovNft(uint64(l))
	l = m.InitialPrice.Size()
	n += 1 + l + sovNft(uint64(l))
	if m.ISOTimestamp != 0 {
		n += 1 + sovNft(uint64(m.ISOTimestamp))
	}
	if m.ISOSuccessPercent != 0 {
		n += 1 + sovNft(uint64(m.ISOSuccessPercent))
	}
	l = len(m.AcceptedPaymentDenom)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	if len(m.Sponsorships) > 0 {
		for _, e := range m.Sponsorships {
			l = e.Size()
			n += 1 + l + sovNft(uint64(l))
		}
	}
	if m.Revenue != nil {
		l = m.Revenue.Size()
		n += 1 + l + sovNft(uint64(l))
	}
	if m.DividendInterval != 0 {
		n += 1 + sovNft(uint64(m.DividendInterval))
	}
	if m.LastDividendTimestamp != 0 {
		n += 1 + sovNft(uint64(m.LastDividendTimestamp))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	if m.Status != 0 {
		n += 2 + sovNft(uint64(m.Status))
	}
	if m.Data != nil {
		l = m.Data.Size()
		n += 2 + l + sovNft(uint64(l))
	}
	return n
}

func (m *Sponsorship) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	return n
}

func (m *Holder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClassId)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovNft(uint64(l))
	}
	l = m.Shares.Size()
	n += 1 + l + sovNft(uint64(l))
	return n
}

func sovNft(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNft(x uint64) (n int) {
	return sovNft(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Class) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Class: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Class: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = &types.Any{}
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NFT) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NFT: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NFT: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Supply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Supply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerEquityPercent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OwnerEquityPercent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailableShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AvailableShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ISOTimestamp", wireType)
			}
			m.ISOTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ISOTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ISOSuccessPercent", wireType)
			}
			m.ISOSuccessPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ISOSuccessPercent |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedPaymentDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AcceptedPaymentDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sponsorships", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sponsorships = append(m.Sponsorships, &Sponsorship{})
			if err := m.Sponsorships[len(m.Sponsorships)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revenue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Revenue == nil {
				m.Revenue = &types1.Coin{}
			}
			if err := m.Revenue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DividendInterval", wireType)
			}
			m.DividendInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DividendInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastDividendTimestamp", wireType)
			}
			m.LastDividendTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastDividendTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= NFTStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = &types.Any{}
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Sponsorship) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sponsorship: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sponsorship: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Holder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Holder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Holder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Shares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNft(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNft
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNft
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNft
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNft
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNft        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNft          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNft = fmt.Errorf("proto: unexpected end of group")
)
