// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flux/astromesh/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Plane int32

const (
	Plane_COSMOS Plane = 0
	Plane_WASM   Plane = 1
	Plane_EVM    Plane = 2
	Plane_SVM    Plane = 3
)

var Plane_name = map[int32]string{
	0: "COSMOS",
	1: "WASM",
	2: "EVM",
	3: "SVM",
}

var Plane_value = map[string]int32{
	"COSMOS": 0,
	"WASM":   1,
	"EVM":    2,
	"SVM":    3,
}

func (x Plane) String() string {
	return proto.EnumName(Plane_name, int32(x))
}

func (Plane) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1e23570b7982a464, []int{0}
}

type MsgChargeVmAccount struct {
	Sender string                                  `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Plane  Plane                                   `protobuf:"varint,2,opt,name=plane,proto3,enum=flux.astromesh.v1beta1.Plane" json:"plane,omitempty"`
	Amount github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,5,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"amount"`
}

func (m *MsgChargeVmAccount) Reset()         { *m = MsgChargeVmAccount{} }
func (m *MsgChargeVmAccount) String() string { return proto.CompactTextString(m) }
func (*MsgChargeVmAccount) ProtoMessage()    {}
func (*MsgChargeVmAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e23570b7982a464, []int{0}
}
func (m *MsgChargeVmAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChargeVmAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChargeVmAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChargeVmAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChargeVmAccount.Merge(m, src)
}
func (m *MsgChargeVmAccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgChargeVmAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChargeVmAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChargeVmAccount proto.InternalMessageInfo

func (m *MsgChargeVmAccount) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgChargeVmAccount) GetPlane() Plane {
	if m != nil {
		return m.Plane
	}
	return Plane_COSMOS
}

type MsgChargeVmAccountResponse struct {
}

func (m *MsgChargeVmAccountResponse) Reset()         { *m = MsgChargeVmAccountResponse{} }
func (m *MsgChargeVmAccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgChargeVmAccountResponse) ProtoMessage()    {}
func (*MsgChargeVmAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e23570b7982a464, []int{1}
}
func (m *MsgChargeVmAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChargeVmAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChargeVmAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChargeVmAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChargeVmAccountResponse.Merge(m, src)
}
func (m *MsgChargeVmAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgChargeVmAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChargeVmAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChargeVmAccountResponse proto.InternalMessageInfo

type MsgDrainVmAccount struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Plane  Plane  `protobuf:"varint,2,opt,name=plane,proto3,enum=flux.astromesh.v1beta1.Plane" json:"plane,omitempty"`
}

func (m *MsgDrainVmAccount) Reset()         { *m = MsgDrainVmAccount{} }
func (m *MsgDrainVmAccount) String() string { return proto.CompactTextString(m) }
func (*MsgDrainVmAccount) ProtoMessage()    {}
func (*MsgDrainVmAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e23570b7982a464, []int{2}
}
func (m *MsgDrainVmAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDrainVmAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDrainVmAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDrainVmAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDrainVmAccount.Merge(m, src)
}
func (m *MsgDrainVmAccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgDrainVmAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDrainVmAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDrainVmAccount proto.InternalMessageInfo

func (m *MsgDrainVmAccount) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgDrainVmAccount) GetPlane() Plane {
	if m != nil {
		return m.Plane
	}
	return Plane_COSMOS
}

type MsgDrainVmAccountResponse struct {
}

func (m *MsgDrainVmAccountResponse) Reset()         { *m = MsgDrainVmAccountResponse{} }
func (m *MsgDrainVmAccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDrainVmAccountResponse) ProtoMessage()    {}
func (*MsgDrainVmAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e23570b7982a464, []int{3}
}
func (m *MsgDrainVmAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDrainVmAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDrainVmAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDrainVmAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDrainVmAccountResponse.Merge(m, src)
}
func (m *MsgDrainVmAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDrainVmAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDrainVmAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDrainVmAccountResponse proto.InternalMessageInfo

type MsgAstroTransfer struct {
	Sender   string                                  `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver string                                  `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	SrcPlane Plane                                   `protobuf:"varint,3,opt,name=src_plane,json=srcPlane,proto3,enum=flux.astromesh.v1beta1.Plane" json:"src_plane,omitempty"`
	DstPlane Plane                                   `protobuf:"varint,4,opt,name=dst_plane,json=dstPlane,proto3,enum=flux.astromesh.v1beta1.Plane" json:"dst_plane,omitempty"`
	Coin     github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,5,opt,name=coin,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"coin"`
}

func (m *MsgAstroTransfer) Reset()         { *m = MsgAstroTransfer{} }
func (m *MsgAstroTransfer) String() string { return proto.CompactTextString(m) }
func (*MsgAstroTransfer) ProtoMessage()    {}
func (*MsgAstroTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e23570b7982a464, []int{4}
}
func (m *MsgAstroTransfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAstroTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAstroTransfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAstroTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAstroTransfer.Merge(m, src)
}
func (m *MsgAstroTransfer) XXX_Size() int {
	return m.Size()
}
func (m *MsgAstroTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAstroTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAstroTransfer proto.InternalMessageInfo

func (m *MsgAstroTransfer) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgAstroTransfer) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *MsgAstroTransfer) GetSrcPlane() Plane {
	if m != nil {
		return m.SrcPlane
	}
	return Plane_COSMOS
}

func (m *MsgAstroTransfer) GetDstPlane() Plane {
	if m != nil {
		return m.DstPlane
	}
	return Plane_COSMOS
}

type MsgAstroTransferResponse struct {
	DestinationDenom []byte `protobuf:"bytes,1,opt,name=destination_denom,json=destinationDenom,proto3" json:"destination_denom,omitempty"`
}

func (m *MsgAstroTransferResponse) Reset()         { *m = MsgAstroTransferResponse{} }
func (m *MsgAstroTransferResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAstroTransferResponse) ProtoMessage()    {}
func (*MsgAstroTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e23570b7982a464, []int{5}
}
func (m *MsgAstroTransferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAstroTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAstroTransferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAstroTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAstroTransferResponse.Merge(m, src)
}
func (m *MsgAstroTransferResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAstroTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAstroTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAstroTransferResponse proto.InternalMessageInfo

func (m *MsgAstroTransferResponse) GetDestinationDenom() []byte {
	if m != nil {
		return m.DestinationDenom
	}
	return nil
}

func init() {
	proto.RegisterEnum("flux.astromesh.v1beta1.Plane", Plane_name, Plane_value)
	proto.RegisterType((*MsgChargeVmAccount)(nil), "flux.astromesh.v1beta1.MsgChargeVmAccount")
	proto.RegisterType((*MsgChargeVmAccountResponse)(nil), "flux.astromesh.v1beta1.MsgChargeVmAccountResponse")
	proto.RegisterType((*MsgDrainVmAccount)(nil), "flux.astromesh.v1beta1.MsgDrainVmAccount")
	proto.RegisterType((*MsgDrainVmAccountResponse)(nil), "flux.astromesh.v1beta1.MsgDrainVmAccountResponse")
	proto.RegisterType((*MsgAstroTransfer)(nil), "flux.astromesh.v1beta1.MsgAstroTransfer")
	proto.RegisterType((*MsgAstroTransferResponse)(nil), "flux.astromesh.v1beta1.MsgAstroTransferResponse")
}

func init() { proto.RegisterFile("flux/astromesh/v1beta1/tx.proto", fileDescriptor_1e23570b7982a464) }

var fileDescriptor_1e23570b7982a464 = []byte{
	// 634 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x4d, 0x4f, 0x13, 0x41,
	0x18, 0xee, 0x52, 0x5a, 0x61, 0x54, 0x2c, 0x2b, 0xd1, 0xb2, 0xe2, 0x42, 0x7a, 0xb1, 0x36, 0xb2,
	0x43, 0x8b, 0x27, 0x6e, 0xa5, 0xca, 0x45, 0x57, 0x4c, 0x4b, 0x6a, 0xe2, 0x41, 0x32, 0xdd, 0x1d,
	0xb6, 0x1b, 0xba, 0x33, 0x75, 0xde, 0x29, 0x41, 0x4f, 0xc4, 0xa3, 0x27, 0x7f, 0x0a, 0x07, 0x7f,
	0x04, 0x47, 0xe2, 0xc9, 0x18, 0x83, 0x06, 0x0e, 0xfc, 0x0d, 0x33, 0xbb, 0xc3, 0xf2, 0xa5, 0xa4,
	0x31, 0xd1, 0xcb, 0xee, 0x3b, 0xf3, 0x3e, 0xcf, 0xfb, 0x35, 0xcf, 0x0c, 0x9a, 0xdd, 0xe8, 0x0d,
	0xb6, 0x31, 0x01, 0x29, 0x78, 0x44, 0xa1, 0x8b, 0xb7, 0xaa, 0x1d, 0x2a, 0x49, 0x15, 0xcb, 0x6d,
	0xa7, 0x2f, 0xb8, 0xe4, 0xe6, 0x1d, 0x05, 0x70, 0x52, 0x80, 0xa3, 0x01, 0xd6, 0xb4, 0xc7, 0x21,
	0xe2, 0xb0, 0x1e, 0xa3, 0x70, 0xb2, 0x48, 0x28, 0xd6, 0xdd, 0x64, 0x85, 0x23, 0x08, 0xf0, 0x56,
	0x55, 0xfd, 0xb4, 0x63, 0x2a, 0xe0, 0x01, 0x4f, 0x08, 0xca, 0xd2, 0xbb, 0x93, 0x24, 0x0a, 0x19,
	0xc7, 0xf1, 0x57, 0x6f, 0xd9, 0x3a, 0x42, 0x87, 0x00, 0x4d, 0x4b, 0xf2, 0x78, 0xc8, 0x12, 0x7f,
	0xe9, 0x87, 0x81, 0x4c, 0x17, 0x82, 0x46, 0x97, 0x88, 0x80, 0xb6, 0xa3, 0xba, 0xe7, 0xf1, 0x01,
	0x93, 0xe6, 0x02, 0xca, 0x03, 0x65, 0x3e, 0x15, 0x45, 0x63, 0xce, 0x28, 0x8f, 0x2f, 0x17, 0xbf,
	0x7c, 0x9e, 0x9f, 0xd2, 0xa5, 0xd5, 0x7d, 0x5f, 0x50, 0x80, 0x96, 0x14, 0x21, 0x0b, 0x9a, 0x1a,
	0x67, 0x2e, 0xa2, 0x5c, 0xbf, 0x47, 0x18, 0x2d, 0x8e, 0xcc, 0x19, 0xe5, 0x89, 0xda, 0x7d, 0xe7,
	0xf7, 0xdd, 0x3a, 0x2f, 0x15, 0xa8, 0x99, 0x60, 0xcd, 0x0e, 0xca, 0x93, 0x48, 0x25, 0x2c, 0xe6,
	0xe6, 0x8c, 0xf2, 0xf5, 0xda, 0xb4, 0xa3, 0x73, 0xa8, 0x72, 0x53, 0x4a, 0x83, 0x87, 0x6c, 0x19,
	0xef, 0x1d, 0xcc, 0x66, 0xbe, 0x1d, 0xcc, 0x3e, 0x08, 0x42, 0xd9, 0x1d, 0x74, 0x1c, 0x8f, 0x47,
	0x7a, 0x56, 0xfa, 0x37, 0x0f, 0xfe, 0x26, 0x96, 0xef, 0xfa, 0x14, 0x62, 0x42, 0x53, 0x47, 0x2e,
	0xcd, 0x20, 0xeb, 0x72, 0x83, 0x4d, 0x0a, 0x7d, 0xce, 0x80, 0x96, 0xde, 0xa3, 0x49, 0x17, 0x82,
	0x27, 0x82, 0x84, 0xec, 0x7f, 0x77, 0x5f, 0xba, 0x87, 0xa6, 0x2f, 0xe5, 0x4e, 0x0b, 0xdb, 0xc9,
	0xa2, 0x82, 0x0b, 0x41, 0x5d, 0x85, 0x58, 0x13, 0x84, 0xc1, 0x06, 0x15, 0x7f, 0x51, 0xd8, 0x63,
	0x34, 0x26, 0xa8, 0x47, 0xc3, 0x2d, 0x2a, 0xe2, 0xda, 0xae, 0xe2, 0xa4, 0x48, 0x73, 0x09, 0x8d,
	0x83, 0xf0, 0xd6, 0x93, 0x96, 0xb2, 0xc3, 0xb4, 0x34, 0x06, 0xc2, 0x8b, 0x2d, 0xc5, 0xf5, 0x41,
	0x6a, 0xee, 0xe8, 0x50, 0x5c, 0x1f, 0x64, 0xc2, 0x7d, 0x83, 0x46, 0x95, 0x36, 0xff, 0x81, 0x1a,
	0xe2, 0xb8, 0x4b, 0x8f, 0x3e, 0x1c, 0xef, 0x56, 0xf4, 0x68, 0x3e, 0x1e, 0xef, 0x56, 0x66, 0x4e,
	0xaf, 0xab, 0xd2, 0x88, 0xe0, 0x00, 0xed, 0xe8, 0x64, 0xda, 0xa5, 0x67, 0xa8, 0x78, 0xf1, 0x04,
	0x4e, 0x8e, 0xc7, 0xc4, 0xe8, 0x76, 0xc8, 0x24, 0x15, 0xc4, 0x93, 0xd4, 0x5f, 0xf7, 0x38, 0x93,
	0xca, 0x8c, 0x8f, 0xe5, 0x46, 0xd3, 0x3c, 0x75, 0x35, 0xb4, 0xa7, 0x82, 0x51, 0x2e, 0xe9, 0x11,
	0xa1, 0x7c, 0x63, 0xb5, 0xe5, 0xae, 0xb6, 0x0a, 0x19, 0x73, 0x0c, 0x8d, 0xbe, 0xaa, 0xb7, 0xdc,
	0x82, 0x61, 0x5e, 0x43, 0xd9, 0xa7, 0x6d, 0xb7, 0x30, 0xa2, 0x8c, 0x56, 0xdb, 0x2d, 0x64, 0x6b,
	0xdf, 0x47, 0x50, 0xd6, 0x85, 0xc0, 0x7c, 0x8b, 0x6e, 0x5d, 0xbc, 0x9d, 0x95, 0x3f, 0xcd, 0xf3,
	0xb2, 0xd0, 0xad, 0xda, 0xf0, 0xd8, 0xb4, 0x39, 0x86, 0x26, 0x2e, 0xdc, 0x88, 0x87, 0x57, 0x44,
	0x39, 0x0f, 0xb5, 0xaa, 0x43, 0x43, 0xd3, 0x7c, 0x9b, 0xe8, 0xe6, 0x79, 0x9d, 0x97, 0xaf, 0x88,
	0x71, 0x0e, 0x69, 0x2d, 0x0c, 0x8b, 0x3c, 0x49, 0x66, 0xe5, 0x76, 0x8e, 0x77, 0x2b, 0xc6, 0xf2,
	0xda, 0xde, 0xa1, 0x6d, 0xec, 0x1f, 0xda, 0xc6, 0xcf, 0x43, 0xdb, 0xf8, 0x74, 0x64, 0x67, 0xf6,
	0x8f, 0xec, 0xcc, 0xd7, 0x23, 0x3b, 0xf3, 0x7a, 0xe9, 0x8c, 0xa6, 0x56, 0x7a, 0x83, 0xed, 0x17,
	0x2b, 0x6b, 0xcf, 0x49, 0x07, 0xb0, 0x4a, 0xe4, 0x63, 0xaf, 0x4b, 0x42, 0x86, 0x23, 0xee, 0x0f,
	0x7a, 0x14, 0xce, 0x3c, 0xf7, 0xb1, 0xd6, 0x3a, 0xf9, 0xf8, 0x55, 0x5d, 0xfc, 0x15, 0x00, 0x00,
	0xff, 0xff, 0xd2, 0xef, 0x5e, 0x34, 0x0d, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ChargeVmAccount(ctx context.Context, in *MsgChargeVmAccount, opts ...grpc.CallOption) (*MsgChargeVmAccountResponse, error)
	DrainVmAccount(ctx context.Context, in *MsgDrainVmAccount, opts ...grpc.CallOption) (*MsgDrainVmAccountResponse, error)
	AstroTransfer(ctx context.Context, in *MsgAstroTransfer, opts ...grpc.CallOption) (*MsgAstroTransferResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ChargeVmAccount(ctx context.Context, in *MsgChargeVmAccount, opts ...grpc.CallOption) (*MsgChargeVmAccountResponse, error) {
	out := new(MsgChargeVmAccountResponse)
	err := c.cc.Invoke(ctx, "/flux.astromesh.v1beta1.Msg/ChargeVmAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DrainVmAccount(ctx context.Context, in *MsgDrainVmAccount, opts ...grpc.CallOption) (*MsgDrainVmAccountResponse, error) {
	out := new(MsgDrainVmAccountResponse)
	err := c.cc.Invoke(ctx, "/flux.astromesh.v1beta1.Msg/DrainVmAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AstroTransfer(ctx context.Context, in *MsgAstroTransfer, opts ...grpc.CallOption) (*MsgAstroTransferResponse, error) {
	out := new(MsgAstroTransferResponse)
	err := c.cc.Invoke(ctx, "/flux.astromesh.v1beta1.Msg/AstroTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ChargeVmAccount(context.Context, *MsgChargeVmAccount) (*MsgChargeVmAccountResponse, error)
	DrainVmAccount(context.Context, *MsgDrainVmAccount) (*MsgDrainVmAccountResponse, error)
	AstroTransfer(context.Context, *MsgAstroTransfer) (*MsgAstroTransferResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ChargeVmAccount(ctx context.Context, req *MsgChargeVmAccount) (*MsgChargeVmAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChargeVmAccount not implemented")
}
func (*UnimplementedMsgServer) DrainVmAccount(ctx context.Context, req *MsgDrainVmAccount) (*MsgDrainVmAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DrainVmAccount not implemented")
}
func (*UnimplementedMsgServer) AstroTransfer(ctx context.Context, req *MsgAstroTransfer) (*MsgAstroTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AstroTransfer not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ChargeVmAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgChargeVmAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ChargeVmAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flux.astromesh.v1beta1.Msg/ChargeVmAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ChargeVmAccount(ctx, req.(*MsgChargeVmAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DrainVmAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDrainVmAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DrainVmAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flux.astromesh.v1beta1.Msg/DrainVmAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DrainVmAccount(ctx, req.(*MsgDrainVmAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AstroTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAstroTransfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AstroTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flux.astromesh.v1beta1.Msg/AstroTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AstroTransfer(ctx, req.(*MsgAstroTransfer))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flux.astromesh.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChargeVmAccount",
			Handler:    _Msg_ChargeVmAccount_Handler,
		},
		{
			MethodName: "DrainVmAccount",
			Handler:    _Msg_DrainVmAccount_Handler,
		},
		{
			MethodName: "AstroTransfer",
			Handler:    _Msg_AstroTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flux/astromesh/v1beta1/tx.proto",
}

func (m *MsgChargeVmAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChargeVmAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChargeVmAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Plane != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Plane))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgChargeVmAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChargeVmAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChargeVmAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDrainVmAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDrainVmAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDrainVmAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Plane != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Plane))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDrainVmAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDrainVmAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDrainVmAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAstroTransfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAstroTransfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAstroTransfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Coin.Size()
		i -= size
		if _, err := m.Coin.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.DstPlane != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DstPlane))
		i--
		dAtA[i] = 0x20
	}
	if m.SrcPlane != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SrcPlane))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAstroTransferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAstroTransferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAstroTransferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DestinationDenom) > 0 {
		i -= len(m.DestinationDenom)
		copy(dAtA[i:], m.DestinationDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DestinationDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgChargeVmAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Plane != 0 {
		n += 1 + sovTx(uint64(m.Plane))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgChargeVmAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDrainVmAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Plane != 0 {
		n += 1 + sovTx(uint64(m.Plane))
	}
	return n
}

func (m *MsgDrainVmAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAstroTransfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SrcPlane != 0 {
		n += 1 + sovTx(uint64(m.SrcPlane))
	}
	if m.DstPlane != 0 {
		n += 1 + sovTx(uint64(m.DstPlane))
	}
	l = m.Coin.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgAstroTransferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DestinationDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgChargeVmAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChargeVmAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChargeVmAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plane", wireType)
			}
			m.Plane = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Plane |= Plane(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgChargeVmAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChargeVmAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChargeVmAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDrainVmAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDrainVmAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDrainVmAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plane", wireType)
			}
			m.Plane = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Plane |= Plane(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDrainVmAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDrainVmAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDrainVmAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAstroTransfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAstroTransfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAstroTransfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcPlane", wireType)
			}
			m.SrcPlane = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SrcPlane |= Plane(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DstPlane", wireType)
			}
			m.DstPlane = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DstPlane |= Plane(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAstroTransferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAstroTransferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAstroTransferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationDenom", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationDenom = append(m.DestinationDenom[:0], dAtA[iNdEx:postIndex]...)
			if m.DestinationDenom == nil {
				m.DestinationDenom = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
