// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flux/strategy/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Config int32

const (
	Config_deploy  Config = 0
	Config_update  Config = 1
	Config_disable Config = 2
	Config_revoke  Config = 3
)

var Config_name = map[int32]string{
	0: "deploy",
	1: "update",
	2: "disable",
	3: "revoke",
}

var Config_value = map[string]int32{
	"deploy":  0,
	"update":  1,
	"disable": 2,
	"revoke":  3,
}

func (x Config) String() string {
	return proto.EnumName(Config_name, int32(x))
}

func (Config) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd40292536fdda88, []int{0}
}

type MsgConfigStrategy struct {
	Sender   string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Config   Config `protobuf:"varint,2,opt,name=config,proto3,enum=flux.strategy.v1beta1.Config" json:"config,omitempty"`
	Id       string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Strategy []byte `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"`
}

func (m *MsgConfigStrategy) Reset()         { *m = MsgConfigStrategy{} }
func (m *MsgConfigStrategy) String() string { return proto.CompactTextString(m) }
func (*MsgConfigStrategy) ProtoMessage()    {}
func (*MsgConfigStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd40292536fdda88, []int{0}
}
func (m *MsgConfigStrategy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfigStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfigStrategy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfigStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfigStrategy.Merge(m, src)
}
func (m *MsgConfigStrategy) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfigStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfigStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfigStrategy proto.InternalMessageInfo

func (m *MsgConfigStrategy) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgConfigStrategy) GetConfig() Config {
	if m != nil {
		return m.Config
	}
	return Config_deploy
}

func (m *MsgConfigStrategy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgConfigStrategy) GetStrategy() []byte {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type MsgConfigStrategyResponse struct {
}

func (m *MsgConfigStrategyResponse) Reset()         { *m = MsgConfigStrategyResponse{} }
func (m *MsgConfigStrategyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgConfigStrategyResponse) ProtoMessage()    {}
func (*MsgConfigStrategyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd40292536fdda88, []int{1}
}
func (m *MsgConfigStrategyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfigStrategyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfigStrategyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfigStrategyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfigStrategyResponse.Merge(m, src)
}
func (m *MsgConfigStrategyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfigStrategyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfigStrategyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfigStrategyResponse proto.InternalMessageInfo

type MsgTriggerStrategies struct {
	Sender string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Ids    []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	Inputs [][]byte `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
}

func (m *MsgTriggerStrategies) Reset()         { *m = MsgTriggerStrategies{} }
func (m *MsgTriggerStrategies) String() string { return proto.CompactTextString(m) }
func (*MsgTriggerStrategies) ProtoMessage()    {}
func (*MsgTriggerStrategies) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd40292536fdda88, []int{2}
}
func (m *MsgTriggerStrategies) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTriggerStrategies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTriggerStrategies.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTriggerStrategies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTriggerStrategies.Merge(m, src)
}
func (m *MsgTriggerStrategies) XXX_Size() int {
	return m.Size()
}
func (m *MsgTriggerStrategies) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTriggerStrategies.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTriggerStrategies proto.InternalMessageInfo

func (m *MsgTriggerStrategies) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgTriggerStrategies) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *MsgTriggerStrategies) GetInputs() [][]byte {
	if m != nil {
		return m.Inputs
	}
	return nil
}

type MsgTriggerStrategiesResponse struct {
}

func (m *MsgTriggerStrategiesResponse) Reset()         { *m = MsgTriggerStrategiesResponse{} }
func (m *MsgTriggerStrategiesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTriggerStrategiesResponse) ProtoMessage()    {}
func (*MsgTriggerStrategiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd40292536fdda88, []int{3}
}
func (m *MsgTriggerStrategiesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTriggerStrategiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTriggerStrategiesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTriggerStrategiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTriggerStrategiesResponse.Merge(m, src)
}
func (m *MsgTriggerStrategiesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTriggerStrategiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTriggerStrategiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTriggerStrategiesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("flux.strategy.v1beta1.Config", Config_name, Config_value)
	proto.RegisterType((*MsgConfigStrategy)(nil), "flux.strategy.v1beta1.MsgConfigStrategy")
	proto.RegisterType((*MsgConfigStrategyResponse)(nil), "flux.strategy.v1beta1.MsgConfigStrategyResponse")
	proto.RegisterType((*MsgTriggerStrategies)(nil), "flux.strategy.v1beta1.MsgTriggerStrategies")
	proto.RegisterType((*MsgTriggerStrategiesResponse)(nil), "flux.strategy.v1beta1.MsgTriggerStrategiesResponse")
}

func init() { proto.RegisterFile("flux/strategy/v1beta1/tx.proto", fileDescriptor_cd40292536fdda88) }

var fileDescriptor_cd40292536fdda88 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xce, 0xc5, 0x60, 0xe8, 0x51, 0x55, 0x89, 0x15, 0xc0, 0x35, 0xd4, 0x8a, 0x22, 0x06, 0x2b,
	0xa8, 0xbe, 0xa6, 0x15, 0x43, 0xbb, 0x51, 0xa4, 0x4e, 0x84, 0xc1, 0xe9, 0xc4, 0x82, 0xec, 0xdc,
	0xf5, 0x7a, 0xc2, 0xf1, 0x59, 0x7e, 0x76, 0x94, 0x6c, 0x88, 0x91, 0x89, 0xbf, 0xc0, 0x3f, 0xc8,
	0xc0, 0x8f, 0x60, 0xac, 0x10, 0x03, 0x23, 0x4a, 0x86, 0xcc, 0xfc, 0x03, 0xe4, 0xf8, 0x1c, 0x50,
	0x9d, 0x4a, 0xc0, 0x62, 0xdf, 0x7b, 0xdf, 0xf7, 0xde, 0xfb, 0xbe, 0x77, 0x3a, 0x6c, 0x5f, 0x84,
	0xd9, 0x84, 0x40, 0x9a, 0xf8, 0x29, 0xe3, 0x53, 0x32, 0xee, 0x05, 0x2c, 0xf5, 0x7b, 0x24, 0x9d,
	0xb8, 0x71, 0x22, 0x53, 0x69, 0xdc, 0xcf, 0x71, 0xb7, 0xc4, 0x5d, 0x85, 0x5b, 0xbb, 0x43, 0x09,
	0x23, 0x09, 0x6f, 0x56, 0x24, 0x52, 0x04, 0x45, 0x85, 0xf5, 0xb0, 0x88, 0xc8, 0x08, 0x38, 0x19,
	0xf7, 0xf2, 0x9f, 0x02, 0x5a, 0x5c, 0x72, 0x59, 0x14, 0xe4, 0x27, 0x95, 0x6d, 0xfa, 0x23, 0x11,
	0x49, 0xb2, 0xfa, 0xaa, 0x94, 0xad, 0x3a, 0x04, 0x3e, 0xb0, 0xb5, 0xa2, 0xa1, 0x14, 0x91, 0xc2,
	0x9f, 0x6c, 0xd6, 0xbc, 0x16, 0xb9, 0x62, 0x75, 0xbe, 0x21, 0xdc, 0xec, 0x03, 0x7f, 0x21, 0xa3,
	0x0b, 0xc1, 0x07, 0x0a, 0x33, 0x0e, 0xb0, 0x0e, 0x2c, 0xa2, 0x2c, 0x31, 0x51, 0x1b, 0x39, 0x5b,
	0xa7, 0xe6, 0xd7, 0xcf, 0xfb, 0x2d, 0xa5, 0xff, 0x39, 0xa5, 0x09, 0x03, 0x18, 0xa4, 0x89, 0x88,
	0xb8, 0xa7, 0x78, 0xc6, 0x33, 0xac, 0x0f, 0x57, 0x3d, 0xcc, 0x7a, 0x1b, 0x39, 0x3b, 0x87, 0x7b,
	0xee, 0xc6, 0x95, 0xb8, 0xc5, 0x20, 0x4f, 0x91, 0x8d, 0x1d, 0x5c, 0x17, 0xd4, 0xd4, 0xf2, 0x21,
	0x5e, 0x5d, 0x50, 0xc3, 0xc2, 0x77, 0xcb, 0x12, 0xf3, 0x56, 0x1b, 0x39, 0xdb, 0xde, 0x3a, 0x3e,
	0xe9, 0xbe, 0x5f, 0xce, 0xba, 0x6a, 0xde, 0x87, 0xe5, 0xac, 0x6b, 0xad, 0xbd, 0x55, 0x0c, 0x74,
	0x1e, 0xe1, 0xdd, 0x4a, 0xd2, 0x63, 0x10, 0xcb, 0x08, 0x58, 0xe7, 0x13, 0xc2, 0xad, 0x3e, 0xf0,
	0xf3, 0x44, 0x70, 0xce, 0x12, 0x05, 0x0b, 0x06, 0xff, 0x61, 0xbb, 0x81, 0x35, 0x41, 0xc1, 0xac,
	0xb7, 0x35, 0x67, 0xcb, 0xcb, 0x8f, 0xc6, 0x03, 0xac, 0x8b, 0x28, 0xce, 0x52, 0x30, 0xb5, 0xb6,
	0xe6, 0x6c, 0x7b, 0x2a, 0x3a, 0xd9, 0xbf, 0xa6, 0x7e, 0xef, 0x4f, 0xf5, 0x15, 0x29, 0x1d, 0x1b,
	0x3f, 0xde, 0x94, 0x2f, 0x3d, 0x74, 0x8f, 0xb1, 0x5e, 0xb8, 0x33, 0x30, 0xd6, 0x29, 0x8b, 0x43,
	0x39, 0x6d, 0xd4, 0xf2, 0x73, 0x16, 0x53, 0x3f, 0x65, 0x0d, 0x64, 0xdc, 0xc3, 0x77, 0xa8, 0x00,
	0x3f, 0x08, 0x59, 0xa3, 0x9e, 0x03, 0x09, 0x1b, 0xcb, 0xb7, 0xac, 0xa1, 0x1d, 0xfe, 0x44, 0x58,
	0xeb, 0x03, 0x37, 0x42, 0xbc, 0x73, 0xed, 0xda, 0x9d, 0x1b, 0x2e, 0xad, 0xb2, 0x4a, 0xeb, 0xe0,
	0x6f, 0x99, 0xa5, 0x60, 0x23, 0xc3, 0xcd, 0xea, 0xc2, 0x9f, 0xde, 0xdc, 0xa6, 0x42, 0xb6, 0x8e,
	0xfe, 0x81, 0x5c, 0x8e, 0xb5, 0x6e, 0xbf, 0x5b, 0xce, 0xba, 0xe8, 0x74, 0xf0, 0x65, 0x6e, 0xa3,
	0xab, 0xb9, 0x8d, 0x7e, 0xcc, 0x6d, 0xf4, 0x71, 0x61, 0xd7, 0xae, 0x16, 0x76, 0xed, 0xfb, 0xc2,
	0xae, 0xbd, 0x3e, 0xe6, 0x22, 0xbd, 0xcc, 0x02, 0x77, 0x28, 0x47, 0xe4, 0x2c, 0xcc, 0x26, 0xaf,
	0xce, 0xce, 0x5f, 0xfa, 0x01, 0x90, 0x7c, 0x16, 0x25, 0xc3, 0x4b, 0x5f, 0x44, 0x64, 0x24, 0x69,
	0x16, 0x32, 0xf8, 0xfd, 0x98, 0xd2, 0x69, 0xcc, 0x20, 0xd0, 0x57, 0x4f, 0xe8, 0xe8, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb6, 0xf7, 0xc2, 0xba, 0x1e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ConfigStrategy(ctx context.Context, in *MsgConfigStrategy, opts ...grpc.CallOption) (*MsgConfigStrategyResponse, error)
	TriggerStrategies(ctx context.Context, in *MsgTriggerStrategies, opts ...grpc.CallOption) (*MsgTriggerStrategiesResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ConfigStrategy(ctx context.Context, in *MsgConfigStrategy, opts ...grpc.CallOption) (*MsgConfigStrategyResponse, error) {
	out := new(MsgConfigStrategyResponse)
	err := c.cc.Invoke(ctx, "/flux.strategy.v1beta1.Msg/ConfigStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TriggerStrategies(ctx context.Context, in *MsgTriggerStrategies, opts ...grpc.CallOption) (*MsgTriggerStrategiesResponse, error) {
	out := new(MsgTriggerStrategiesResponse)
	err := c.cc.Invoke(ctx, "/flux.strategy.v1beta1.Msg/TriggerStrategies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ConfigStrategy(context.Context, *MsgConfigStrategy) (*MsgConfigStrategyResponse, error)
	TriggerStrategies(context.Context, *MsgTriggerStrategies) (*MsgTriggerStrategiesResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ConfigStrategy(ctx context.Context, req *MsgConfigStrategy) (*MsgConfigStrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigStrategy not implemented")
}
func (*UnimplementedMsgServer) TriggerStrategies(ctx context.Context, req *MsgTriggerStrategies) (*MsgTriggerStrategiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerStrategies not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ConfigStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConfigStrategy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConfigStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flux.strategy.v1beta1.Msg/ConfigStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConfigStrategy(ctx, req.(*MsgConfigStrategy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TriggerStrategies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTriggerStrategies)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TriggerStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flux.strategy.v1beta1.Msg/TriggerStrategies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TriggerStrategies(ctx, req.(*MsgTriggerStrategies))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flux.strategy.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigStrategy",
			Handler:    _Msg_ConfigStrategy_Handler,
		},
		{
			MethodName: "TriggerStrategies",
			Handler:    _Msg_TriggerStrategies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flux/strategy/v1beta1/tx.proto",
}

func (m *MsgConfigStrategy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfigStrategy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfigStrategy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Strategy) > 0 {
		i -= len(m.Strategy)
		copy(dAtA[i:], m.Strategy)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Strategy)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Config != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Config))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgConfigStrategyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfigStrategyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfigStrategyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgTriggerStrategies) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTriggerStrategies) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTriggerStrategies) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Inputs) > 0 {
		for iNdEx := len(m.Inputs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Inputs[iNdEx])
			copy(dAtA[i:], m.Inputs[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Inputs[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Ids) > 0 {
		for iNdEx := len(m.Ids) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Ids[iNdEx])
			copy(dAtA[i:], m.Ids[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Ids[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTriggerStrategiesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTriggerStrategiesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTriggerStrategiesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgConfigStrategy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Config != 0 {
		n += 1 + sovTx(uint64(m.Config))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Strategy)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgConfigStrategyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgTriggerStrategies) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Ids) > 0 {
		for _, s := range m.Ids {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.Inputs) > 0 {
		for _, b := range m.Inputs {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgTriggerStrategiesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgConfigStrategy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfigStrategy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfigStrategy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			m.Config = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Config |= Config(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Strategy", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Strategy = append(m.Strategy[:0], dAtA[iNdEx:postIndex]...)
			if m.Strategy == nil {
				m.Strategy = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfigStrategyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfigStrategyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfigStrategyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTriggerStrategies) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTriggerStrategies: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTriggerStrategies: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ids", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ids = append(m.Ids, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inputs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inputs = append(m.Inputs, make([]byte, postIndex-iNdEx))
			copy(m.Inputs[len(m.Inputs)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTriggerStrategiesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTriggerStrategiesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTriggerStrategiesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
