// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flux/stream/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/FluxNFTLabs/sdk-go/chain/modules/bazaar/types"
	_ "github.com/FluxNFTLabs/sdk-go/chain/modules/fnft/types"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// WARNING: always append to bottom or you will mess up indexer logic
type Op int32

const (
	// Synthetic events
	Op_SyntheticUpdate Op = 0
	// FNFT
	Op_FNFTUpdateClass        Op = 100
	Op_FNFTCreate             Op = 101
	Op_FNFTPurchaseShares     Op = 102
	Op_FNFTSponsor            Op = 103
	Op_FNFTUpdateRevenue      Op = 104
	Op_FNFTISO                Op = 105
	Op_FNFTDividend           Op = 106
	Op_FNFTUpdateHolderCount  Op = 107
	Op_FNFTUpdateProductCount Op = 108
	Op_FNFTUpdateHolder       Op = 109
	Op_FNFTDeleteHolder       Op = 110
	// BAZAAR
	// product events
	Op_BazaarCreateProduct    Op = 200
	Op_BazaarPurchaseOffering Op = 201
	Op_BazaarVerifyProduct    Op = 202
	// EVM
	Op_EvmDeployContract Op = 3000
	Op_EvmExecute        Op = 3001
	Op_EvmEmitLog        Op = 3002
	// SVM
	Op_SvmExecute Op = 4000
	// astromesh
	Op_BankUpdate Op = 5000
)

var Op_name = map[int32]string{
	0:    "SyntheticUpdate",
	100:  "FNFTUpdateClass",
	101:  "FNFTCreate",
	102:  "FNFTPurchaseShares",
	103:  "FNFTSponsor",
	104:  "FNFTUpdateRevenue",
	105:  "FNFTISO",
	106:  "FNFTDividend",
	107:  "FNFTUpdateHolderCount",
	108:  "FNFTUpdateProductCount",
	109:  "FNFTUpdateHolder",
	110:  "FNFTDeleteHolder",
	200:  "BazaarCreateProduct",
	201:  "BazaarPurchaseOffering",
	202:  "BazaarVerifyProduct",
	3000: "EvmDeployContract",
	3001: "EvmExecute",
	3002: "EvmEmitLog",
	4000: "SvmExecute",
	5000: "BankUpdate",
}

var Op_value = map[string]int32{
	"SyntheticUpdate":        0,
	"FNFTUpdateClass":        100,
	"FNFTCreate":             101,
	"FNFTPurchaseShares":     102,
	"FNFTSponsor":            103,
	"FNFTUpdateRevenue":      104,
	"FNFTISO":                105,
	"FNFTDividend":           106,
	"FNFTUpdateHolderCount":  107,
	"FNFTUpdateProductCount": 108,
	"FNFTUpdateHolder":       109,
	"FNFTDeleteHolder":       110,
	"BazaarCreateProduct":    200,
	"BazaarPurchaseOffering": 201,
	"BazaarVerifyProduct":    202,
	"EvmDeployContract":      3000,
	"EvmExecute":             3001,
	"EvmEmitLog":             3002,
	"SvmExecute":             4000,
	"BankUpdate":             5000,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}

func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a82db9e8fada1d29, []int{0}
}

type EventsRequest struct {
	Height    uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Modules   []string `protobuf:"bytes,2,rep,name=modules,proto3" json:"modules,omitempty"`
	TmQueries []string `protobuf:"bytes,3,rep,name=tm_queries,json=tmQueries,proto3" json:"tm_queries,omitempty"`
}

func (m *EventsRequest) Reset()         { *m = EventsRequest{} }
func (m *EventsRequest) String() string { return proto.CompactTextString(m) }
func (*EventsRequest) ProtoMessage()    {}
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a82db9e8fada1d29, []int{0}
}
func (m *EventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsRequest.Merge(m, src)
}
func (m *EventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *EventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsRequest proto.InternalMessageInfo

func (m *EventsRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *EventsRequest) GetModules() []string {
	if m != nil {
		return m.Modules
	}
	return nil
}

func (m *EventsRequest) GetTmQueries() []string {
	if m != nil {
		return m.TmQueries
	}
	return nil
}

type EventsResponse struct {
	Height    uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Time      uint64   `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Modules   []string `protobuf:"bytes,3,rep,name=modules,proto3" json:"modules,omitempty"`
	Events    []*Event `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	TmQueries []string `protobuf:"bytes,5,rep,name=tm_queries,json=tmQueries,proto3" json:"tm_queries,omitempty"`
	TmData    []string `protobuf:"bytes,6,rep,name=tm_data,json=tmData,proto3" json:"tm_data,omitempty"`
}

func (m *EventsResponse) Reset()         { *m = EventsResponse{} }
func (m *EventsResponse) String() string { return proto.CompactTextString(m) }
func (*EventsResponse) ProtoMessage()    {}
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a82db9e8fada1d29, []int{1}
}
func (m *EventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsResponse.Merge(m, src)
}
func (m *EventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *EventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventsResponse proto.InternalMessageInfo

func (m *EventsResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *EventsResponse) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *EventsResponse) GetModules() []string {
	if m != nil {
		return m.Modules
	}
	return nil
}

func (m *EventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *EventsResponse) GetTmQueries() []string {
	if m != nil {
		return m.TmQueries
	}
	return nil
}

func (m *EventsResponse) GetTmData() []string {
	if m != nil {
		return m.TmData
	}
	return nil
}

type Event struct {
	EventOps []*EventOp `protobuf:"bytes,1,rep,name=event_ops,json=eventOps,proto3" json:"event_ops,omitempty"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_a82db9e8fada1d29, []int{2}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Event.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return m.Size()
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventOps() []*EventOp {
	if m != nil {
		return m.EventOps
	}
	return nil
}

type EventOp struct {
	Op     Op         `protobuf:"varint,1,opt,name=op,proto3,enum=flux.stream.v1beta1.Op" json:"op,omitempty"`
	Module string     `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Data   *types.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *EventOp) Reset()         { *m = EventOp{} }
func (m *EventOp) String() string { return proto.CompactTextString(m) }
func (*EventOp) ProtoMessage()    {}
func (*EventOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a82db9e8fada1d29, []int{3}
}
func (m *EventOp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventOp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventOp.Merge(m, src)
}
func (m *EventOp) XXX_Size() int {
	return m.Size()
}
func (m *EventOp) XXX_DiscardUnknown() {
	xxx_messageInfo_EventOp.DiscardUnknown(m)
}

var xxx_messageInfo_EventOp proto.InternalMessageInfo

func (m *EventOp) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_SyntheticUpdate
}

func (m *EventOp) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *EventOp) GetData() *types.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type SyncStatus struct {
	LastBlock      uint64 `protobuf:"varint,1,opt,name=last_block,json=lastBlock,proto3" json:"last_block,omitempty"`
	LastBlockTime  int64  `protobuf:"varint,2,opt,name=last_block_time,json=lastBlockTime,proto3" json:"last_block_time,omitempty"`
	UpdatedAt      int64  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CurrentVersion string `protobuf:"bytes,4,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
}

func (m *SyncStatus) Reset()         { *m = SyncStatus{} }
func (m *SyncStatus) String() string { return proto.CompactTextString(m) }
func (*SyncStatus) ProtoMessage()    {}
func (*SyncStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_a82db9e8fada1d29, []int{4}
}
func (m *SyncStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncStatus.Merge(m, src)
}
func (m *SyncStatus) XXX_Size() int {
	return m.Size()
}
func (m *SyncStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SyncStatus proto.InternalMessageInfo

func (m *SyncStatus) GetLastBlock() uint64 {
	if m != nil {
		return m.LastBlock
	}
	return 0
}

func (m *SyncStatus) GetLastBlockTime() int64 {
	if m != nil {
		return m.LastBlockTime
	}
	return 0
}

func (m *SyncStatus) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *SyncStatus) GetCurrentVersion() string {
	if m != nil {
		return m.CurrentVersion
	}
	return ""
}

func init() {
	proto.RegisterEnum("flux.stream.v1beta1.Op", Op_name, Op_value)
	proto.RegisterType((*EventsRequest)(nil), "flux.stream.v1beta1.EventsRequest")
	proto.RegisterType((*EventsResponse)(nil), "flux.stream.v1beta1.EventsResponse")
	proto.RegisterType((*Event)(nil), "flux.stream.v1beta1.Event")
	proto.RegisterType((*EventOp)(nil), "flux.stream.v1beta1.EventOp")
	proto.RegisterType((*SyncStatus)(nil), "flux.stream.v1beta1.SyncStatus")
}

func init() { proto.RegisterFile("flux/stream/v1beta1/query.proto", fileDescriptor_a82db9e8fada1d29) }

var fileDescriptor_a82db9e8fada1d29 = []byte{
	// 873 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x31, 0x73, 0x1b, 0x45,
	0x14, 0xf6, 0x49, 0xb6, 0x8c, 0x9e, 0x13, 0xeb, 0xb2, 0x4e, 0xec, 0x8b, 0x92, 0x28, 0x46, 0xcc,
	0x60, 0x0d, 0xc5, 0x1d, 0x11, 0x15, 0xc3, 0x50, 0x58, 0xb2, 0x0d, 0x9e, 0xc9, 0x44, 0xe1, 0x64,
	0x52, 0xd0, 0x88, 0xd5, 0xdd, 0x9e, 0x74, 0xf8, 0x6e, 0xf7, 0x72, 0xfb, 0x4e, 0x63, 0xe1, 0x71,
	0x43, 0x45, 0xc9, 0x0c, 0x15, 0x43, 0x43, 0x41, 0x4b, 0x0f, 0x94, 0x54, 0x21, 0x55, 0x66, 0x68,
	0x28, 0x19, 0x9b, 0x1f, 0xc2, 0xec, 0xde, 0x49, 0x02, 0x8f, 0xcd, 0x50, 0xd0, 0xdd, 0xfb, 0xbe,
	0xef, 0xbd, 0xef, 0xed, 0xbb, 0x7d, 0x0b, 0x0f, 0x83, 0x28, 0x3b, 0x71, 0x24, 0xa6, 0x8c, 0xc6,
	0xce, 0xe4, 0xd1, 0x90, 0x21, 0x7d, 0xe4, 0x3c, 0xcf, 0x58, 0x3a, 0xb5, 0x93, 0x54, 0xa0, 0x20,
	0x1b, 0x4a, 0x60, 0xe7, 0x02, 0xbb, 0x10, 0xd4, 0xef, 0x8e, 0x84, 0x18, 0x45, 0xcc, 0xd1, 0x92,
	0x61, 0x16, 0x38, 0x94, 0x17, 0xfa, 0xfa, 0xfd, 0x82, 0xa2, 0x49, 0xe8, 0x50, 0xce, 0x05, 0x52,
	0x0c, 0x05, 0x97, 0x05, 0x7b, 0x4f, 0xdb, 0x05, 0x3c, 0xc0, 0xb9, 0x19, 0x0f, 0xb0, 0x20, 0x5f,
	0xd7, 0xe4, 0x90, 0x7e, 0x4e, 0x69, 0x3a, 0xa7, 0x93, 0x54, 0xf8, 0x99, 0x57, 0x48, 0x9a, 0x9f,
	0xc2, 0xcd, 0xfd, 0x09, 0xe3, 0x28, 0x5d, 0xf6, 0x3c, 0x63, 0x12, 0xc9, 0x26, 0x54, 0xc6, 0x2c,
	0x1c, 0x8d, 0xd1, 0x32, 0xb6, 0x8d, 0xd6, 0xb2, 0x5b, 0x44, 0xc4, 0x82, 0xd5, 0x58, 0xf8, 0x59,
	0xc4, 0xa4, 0x55, 0xda, 0x2e, 0xb7, 0xaa, 0xee, 0x2c, 0x24, 0x0f, 0x00, 0x30, 0x1e, 0xa8, 0x23,
	0x86, 0x4c, 0x5a, 0x65, 0x4d, 0x56, 0x31, 0xfe, 0x28, 0x07, 0x9a, 0xbf, 0x18, 0xb0, 0x3e, 0xb3,
	0x90, 0x89, 0xe0, 0x92, 0x5d, 0xeb, 0x41, 0x60, 0x19, 0xc3, 0x98, 0x59, 0x25, 0x8d, 0xea, 0xef,
	0xbf, 0xfb, 0x96, 0xff, 0xe9, 0xdb, 0x86, 0x0a, 0xd3, 0x75, 0xad, 0xe5, 0xed, 0x72, 0x6b, 0xad,
	0x5d, 0xb7, 0xaf, 0x98, 0xac, 0xad, 0xad, 0xdd, 0x42, 0x79, 0xa9, 0xd7, 0x95, 0x4b, 0xbd, 0x92,
	0x2d, 0x58, 0xc5, 0x78, 0xe0, 0x53, 0xa4, 0x56, 0x45, 0x73, 0x15, 0x8c, 0xf7, 0x28, 0xd2, 0x66,
	0x07, 0x56, 0x74, 0x21, 0xf2, 0x2e, 0x54, 0x75, 0xa9, 0x81, 0x48, 0xa4, 0x65, 0x68, 0xdf, 0xfb,
	0xd7, 0xfb, 0xf6, 0x12, 0xf7, 0x35, 0x96, 0x7f, 0xc8, 0x26, 0xc2, 0x6a, 0x01, 0x92, 0x1d, 0x28,
	0x89, 0x44, 0x1f, 0x7e, 0xbd, 0xbd, 0x75, 0x65, 0x7a, 0x2f, 0x71, 0x4b, 0x22, 0x51, 0x93, 0xca,
	0x8f, 0xab, 0x67, 0x52, 0x75, 0x8b, 0x88, 0xb4, 0x60, 0x59, 0x77, 0x59, 0xde, 0x36, 0x5a, 0x6b,
	0xed, 0xdb, 0x76, 0x7e, 0x47, 0xec, 0xd9, 0xf5, 0xb1, 0x77, 0xf9, 0xd4, 0xd5, 0x8a, 0xe6, 0xb7,
	0x06, 0x40, 0x7f, 0xca, 0xbd, 0x3e, 0x52, 0xcc, 0xf4, 0x00, 0x22, 0x2a, 0x71, 0x30, 0x8c, 0x84,
	0x77, 0x5c, 0x8c, 0xbf, 0xaa, 0x90, 0x8e, 0x02, 0xc8, 0x9b, 0x50, 0x5b, 0xd0, 0x83, 0xf9, 0xcf,
	0x28, 0xbb, 0x37, 0xe7, 0x9a, 0x23, 0xf5, 0x57, 0x1e, 0x00, 0x64, 0x89, 0x4f, 0x91, 0xf9, 0x03,
	0x8a, 0xba, 0x8b, 0xb2, 0x5b, 0x2d, 0x90, 0x5d, 0x24, 0x3b, 0x50, 0xf3, 0xb2, 0x34, 0x55, 0x73,
	0x9a, 0xb0, 0x54, 0x86, 0x82, 0x5b, 0xcb, 0xba, 0xff, 0xf5, 0x02, 0x7e, 0x96, 0xa3, 0x6f, 0xfd,
	0x50, 0x86, 0x52, 0x2f, 0x21, 0x1b, 0x50, 0xeb, 0x4f, 0x39, 0x8e, 0x19, 0x86, 0xde, 0xc7, 0xba,
	0x8a, 0xb9, 0xa4, 0xc0, 0x83, 0x27, 0x07, 0x47, 0x79, 0xdc, 0x8d, 0xa8, 0x94, 0xa6, 0x4f, 0xd6,
	0x01, 0x14, 0xd8, 0x4d, 0x99, 0x12, 0xa9, 0xab, 0x44, 0x54, 0xfc, 0x34, 0x4b, 0xbd, 0x31, 0x95,
	0xac, 0x3f, 0xa6, 0x29, 0x93, 0x66, 0x40, 0x6a, 0xb0, 0xa6, 0xf0, 0xbe, 0xba, 0x70, 0x22, 0x35,
	0x47, 0xe4, 0x0e, 0xdc, 0x5a, 0x54, 0x73, 0xd5, 0x4f, 0xc9, 0x98, 0x39, 0x26, 0x6b, 0xb0, 0xaa,
	0xe0, 0xc3, 0x7e, 0xcf, 0x0c, 0x89, 0x09, 0x37, 0x54, 0xb0, 0x17, 0x4e, 0x42, 0x9f, 0x71, 0xdf,
	0xfc, 0x8c, 0xdc, 0x85, 0x3b, 0x8b, 0xac, 0x0f, 0x45, 0xe4, 0xb3, 0xb4, 0x2b, 0x32, 0x8e, 0xe6,
	0x31, 0xa9, 0xc3, 0xe6, 0x82, 0x7a, 0x9a, 0x2f, 0x55, 0xce, 0x45, 0xe4, 0x36, 0x98, 0x97, 0xd3,
	0xcc, 0x78, 0x86, 0xee, 0xb1, 0x88, 0xcd, 0x51, 0x4e, 0x2c, 0xd8, 0xe8, 0xe8, 0x0d, 0xcd, 0xcf,
	0x54, 0x54, 0x32, 0x5f, 0x18, 0xe4, 0x1e, 0x6c, 0xe6, 0xcc, 0xec, 0x74, 0xbd, 0x20, 0x60, 0x69,
	0xc8, 0x47, 0xe6, 0xaf, 0xc6, 0x22, 0xed, 0x19, 0x4b, 0xc3, 0x60, 0x3a, 0x4b, 0x7b, 0x69, 0x90,
	0x4d, 0xb8, 0xb5, 0x3f, 0x89, 0xf7, 0x58, 0x12, 0x89, 0x69, 0x57, 0x70, 0x4c, 0xa9, 0x87, 0xe6,
	0x8f, 0x5b, 0xa4, 0x06, 0xb0, 0x3f, 0x89, 0xf7, 0x4f, 0x98, 0x97, 0x21, 0x33, 0x7f, 0x9a, 0x03,
	0x71, 0x88, 0x8f, 0xc5, 0xc8, 0xfc, 0x59, 0x03, 0xfd, 0x85, 0xe2, 0xbb, 0x87, 0x0a, 0xe8, 0x50,
	0x7e, 0x5c, 0xfc, 0x92, 0x2f, 0x77, 0xda, 0x2f, 0x4b, 0xb0, 0xa2, 0x96, 0x65, 0x4a, 0xbe, 0x31,
	0xa0, 0xfa, 0x01, 0xc3, 0x7c, 0xb3, 0x49, 0xf3, 0xfa, 0x1d, 0x98, 0xbd, 0x2c, 0xf5, 0x37, 0xfe,
	0x55, 0x93, 0x3f, 0x0d, 0xcd, 0xee, 0x17, 0xbf, 0xfd, 0xf9, 0x75, 0xe9, 0x7d, 0xf2, 0x9e, 0x73,
	0xd5, 0x3b, 0x9a, 0x6f, 0xb1, 0x73, 0x9a, 0xbf, 0x17, 0x67, 0xce, 0x69, 0xf1, 0x16, 0x9c, 0x39,
	0xa7, 0x8b, 0xb5, 0x3e, 0x23, 0xdf, 0x1b, 0x70, 0xa3, 0xaf, 0x33, 0xff, 0xef, 0xf6, 0x0e, 0x75,
	0x7b, 0x5d, 0xb2, 0x7b, 0x65, 0x7b, 0x79, 0xf8, 0xdf, 0x9a, 0x7c, 0xdb, 0xe8, 0x1c, 0xbe, 0x38,
	0x6f, 0x18, 0xaf, 0xce, 0x1b, 0xc6, 0x1f, 0xe7, 0x0d, 0xe3, 0xab, 0x8b, 0xc6, 0xd2, 0xab, 0x8b,
	0xc6, 0xd2, 0xef, 0x17, 0x8d, 0xa5, 0x4f, 0x9c, 0x51, 0x88, 0xe3, 0x6c, 0x68, 0x7b, 0x22, 0x76,
	0x0e, 0xa2, 0xec, 0xe4, 0xc9, 0xc1, 0xd1, 0x63, 0x3a, 0x94, 0xda, 0xd4, 0x77, 0xbc, 0x31, 0x0d,
	0xf9, 0xcc, 0x1b, 0xa7, 0x09, 0x93, 0xc3, 0x8a, 0xde, 0xfc, 0x77, 0xfe, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0xd2, 0xab, 0x83, 0xb3, 0x7e, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	GetEvents(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (*EventsResponse, error)
	StreamEvents(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (Query_StreamEventsClient, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetEvents(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (*EventsResponse, error) {
	out := new(EventsResponse)
	err := c.cc.Invoke(ctx, "/flux.stream.v1beta1.Query/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StreamEvents(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (Query_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Query_serviceDesc.Streams[0], "/flux.stream.v1beta1.Query/StreamEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &queryStreamEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Query_StreamEventsClient interface {
	Recv() (*EventsResponse, error)
	grpc.ClientStream
}

type queryStreamEventsClient struct {
	grpc.ClientStream
}

func (x *queryStreamEventsClient) Recv() (*EventsResponse, error) {
	m := new(EventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	GetEvents(context.Context, *EventsRequest) (*EventsResponse, error)
	StreamEvents(*EventsRequest, Query_StreamEventsServer) error
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetEvents(ctx context.Context, req *EventsRequest) (*EventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (*UnimplementedQueryServer) StreamEvents(req *EventsRequest, srv Query_StreamEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flux.stream.v1beta1.Query/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetEvents(ctx, req.(*EventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).StreamEvents(m, &queryStreamEventsServer{stream})
}

type Query_StreamEventsServer interface {
	Send(*EventsResponse) error
	grpc.ServerStream
}

type queryStreamEventsServer struct {
	grpc.ServerStream
}

func (x *queryStreamEventsServer) Send(m *EventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flux.stream.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvents",
			Handler:    _Query_GetEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _Query_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "flux/stream/v1beta1/query.proto",
}

func (m *EventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TmQueries) > 0 {
		for iNdEx := len(m.TmQueries) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TmQueries[iNdEx])
			copy(dAtA[i:], m.TmQueries[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.TmQueries[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Modules) > 0 {
		for iNdEx := len(m.Modules) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Modules[iNdEx])
			copy(dAtA[i:], m.Modules[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Modules[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Height != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TmData) > 0 {
		for iNdEx := len(m.TmData) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TmData[iNdEx])
			copy(dAtA[i:], m.TmData[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.TmData[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.TmQueries) > 0 {
		for iNdEx := len(m.TmQueries) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TmQueries[iNdEx])
			copy(dAtA[i:], m.TmQueries[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.TmQueries[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Events) > 0 {
		for iNdEx := len(m.Events) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Events[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Modules) > 0 {
		for iNdEx := len(m.Modules) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Modules[iNdEx])
			copy(dAtA[i:], m.Modules[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Modules[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Time != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Time))
		i--
		dAtA[i] = 0x10
	}
	if m.Height != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Event) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Event) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EventOps) > 0 {
		for iNdEx := len(m.EventOps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EventOps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *EventOp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventOp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventOp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Data != nil {
		{
			size, err := m.Data.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0x12
	}
	if m.Op != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Op))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SyncStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CurrentVersion) > 0 {
		i -= len(m.CurrentVersion)
		copy(dAtA[i:], m.CurrentVersion)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CurrentVersion)))
		i--
		dAtA[i] = 0x22
	}
	if m.UpdatedAt != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x18
	}
	if m.LastBlockTime != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LastBlockTime))
		i--
		dAtA[i] = 0x10
	}
	if m.LastBlock != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LastBlock))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovQuery(uint64(m.Height))
	}
	if len(m.Modules) > 0 {
		for _, s := range m.Modules {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.TmQueries) > 0 {
		for _, s := range m.TmQueries {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *EventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovQuery(uint64(m.Height))
	}
	if m.Time != 0 {
		n += 1 + sovQuery(uint64(m.Time))
	}
	if len(m.Modules) > 0 {
		for _, s := range m.Modules {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.Events) > 0 {
		for _, e := range m.Events {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.TmQueries) > 0 {
		for _, s := range m.TmQueries {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.TmData) > 0 {
		for _, s := range m.TmData {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *Event) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.EventOps) > 0 {
		for _, e := range m.EventOps {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *EventOp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Op != 0 {
		n += 1 + sovQuery(uint64(m.Op))
	}
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Data != nil {
		l = m.Data.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *SyncStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LastBlock != 0 {
		n += 1 + sovQuery(uint64(m.LastBlock))
	}
	if m.LastBlockTime != 0 {
		n += 1 + sovQuery(uint64(m.LastBlockTime))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovQuery(uint64(m.UpdatedAt))
	}
	l = len(m.CurrentVersion)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Modules", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Modules = append(m.Modules, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TmQueries", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TmQueries = append(m.TmQueries, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Modules", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Modules = append(m.Modules, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Events", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Events = append(m.Events, &Event{})
			if err := m.Events[len(m.Events)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TmQueries", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TmQueries = append(m.TmQueries, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TmData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TmData = append(m.TmData, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Event) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventOps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventOps = append(m.EventOps, &EventOp{})
			if err := m.EventOps[len(m.EventOps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventOp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventOp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventOp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Op", wireType)
			}
			m.Op = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Op |= Op(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = &types.Any{}
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastBlock", wireType)
			}
			m.LastBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastBlockTime", wireType)
			}
			m.LastBlockTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastBlockTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
