// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package drift

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// LiquidatePerpWithFill is the `liquidatePerpWithFill` instruction.
type LiquidatePerpWithFill struct {
	MarketIndex *uint16

	// [0] = [] state
	//
	// [1] = [SIGNER] authority
	//
	// [2] = [WRITE] liquidator
	//
	// [3] = [WRITE] liquidatorStats
	//
	// [4] = [WRITE] user
	//
	// [5] = [WRITE] userStats
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewLiquidatePerpWithFillInstructionBuilder creates a new `LiquidatePerpWithFill` instruction builder.
func NewLiquidatePerpWithFillInstructionBuilder() *LiquidatePerpWithFill {
	nd := &LiquidatePerpWithFill{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetMarketIndex sets the "marketIndex" parameter.
func (inst *LiquidatePerpWithFill) SetMarketIndex(marketIndex uint16) *LiquidatePerpWithFill {
	inst.MarketIndex = &marketIndex
	return inst
}

// SetStateAccount sets the "state" account.
func (inst *LiquidatePerpWithFill) SetStateAccount(state ag_solanago.PublicKey) *LiquidatePerpWithFill {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(state)
	return inst
}

// GetStateAccount gets the "state" account.
func (inst *LiquidatePerpWithFill) GetStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *LiquidatePerpWithFill) SetAuthorityAccount(authority ag_solanago.PublicKey) *LiquidatePerpWithFill {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *LiquidatePerpWithFill) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetLiquidatorAccount sets the "liquidator" account.
func (inst *LiquidatePerpWithFill) SetLiquidatorAccount(liquidator ag_solanago.PublicKey) *LiquidatePerpWithFill {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(liquidator).WRITE()
	return inst
}

// GetLiquidatorAccount gets the "liquidator" account.
func (inst *LiquidatePerpWithFill) GetLiquidatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetLiquidatorStatsAccount sets the "liquidatorStats" account.
func (inst *LiquidatePerpWithFill) SetLiquidatorStatsAccount(liquidatorStats ag_solanago.PublicKey) *LiquidatePerpWithFill {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(liquidatorStats).WRITE()
	return inst
}

// GetLiquidatorStatsAccount gets the "liquidatorStats" account.
func (inst *LiquidatePerpWithFill) GetLiquidatorStatsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetUserAccount sets the "user" account.
func (inst *LiquidatePerpWithFill) SetUserAccount(user ag_solanago.PublicKey) *LiquidatePerpWithFill {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(user).WRITE()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *LiquidatePerpWithFill) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetUserStatsAccount sets the "userStats" account.
func (inst *LiquidatePerpWithFill) SetUserStatsAccount(userStats ag_solanago.PublicKey) *LiquidatePerpWithFill {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(userStats).WRITE()
	return inst
}

// GetUserStatsAccount gets the "userStats" account.
func (inst *LiquidatePerpWithFill) GetUserStatsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst LiquidatePerpWithFill) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_LiquidatePerpWithFill,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst LiquidatePerpWithFill) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *LiquidatePerpWithFill) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.MarketIndex == nil {
			return errors.New("MarketIndex parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.State is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Liquidator is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.LiquidatorStats is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.UserStats is not set")
		}
	}
	return nil
}

func (inst *LiquidatePerpWithFill) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("LiquidatePerpWithFill")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("MarketIndex", *inst.MarketIndex))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("          state", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("      authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("     liquidator", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("liquidatorStats", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("           user", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("      userStats", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj LiquidatePerpWithFill) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `MarketIndex` param:
	err = encoder.Encode(obj.MarketIndex)
	if err != nil {
		return err
	}
	return nil
}
func (obj *LiquidatePerpWithFill) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `MarketIndex`:
	err = decoder.Decode(&obj.MarketIndex)
	if err != nil {
		return err
	}
	return nil
}

// NewLiquidatePerpWithFillInstruction declares a new LiquidatePerpWithFill instruction with the provided parameters and accounts.
func NewLiquidatePerpWithFillInstruction(
	// Parameters:
	marketIndex uint16,
	// Accounts:
	state ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	liquidator ag_solanago.PublicKey,
	liquidatorStats ag_solanago.PublicKey,
	user ag_solanago.PublicKey,
	userStats ag_solanago.PublicKey) *LiquidatePerpWithFill {
	return NewLiquidatePerpWithFillInstructionBuilder().
		SetMarketIndex(marketIndex).
		SetStateAccount(state).
		SetAuthorityAccount(authority).
		SetLiquidatorAccount(liquidator).
		SetLiquidatorStatsAccount(liquidatorStats).
		SetUserAccount(user).
		SetUserStatsAccount(userStats)
}
