// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package drift

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RecenterPerpMarketAmm is the `recenterPerpMarketAmm` instruction.
type RecenterPerpMarketAmm struct {
	PegMultiplier *ag_binary.Uint128
	SqrtK         *ag_binary.Uint128

	// [0] = [SIGNER] admin
	//
	// [1] = [] state
	//
	// [2] = [WRITE] perpMarket
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRecenterPerpMarketAmmInstructionBuilder creates a new `RecenterPerpMarketAmm` instruction builder.
func NewRecenterPerpMarketAmmInstructionBuilder() *RecenterPerpMarketAmm {
	nd := &RecenterPerpMarketAmm{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetPegMultiplier sets the "pegMultiplier" parameter.
func (inst *RecenterPerpMarketAmm) SetPegMultiplier(pegMultiplier ag_binary.Uint128) *RecenterPerpMarketAmm {
	inst.PegMultiplier = &pegMultiplier
	return inst
}

// SetSqrtK sets the "sqrtK" parameter.
func (inst *RecenterPerpMarketAmm) SetSqrtK(sqrtK ag_binary.Uint128) *RecenterPerpMarketAmm {
	inst.SqrtK = &sqrtK
	return inst
}

// SetAdminAccount sets the "admin" account.
func (inst *RecenterPerpMarketAmm) SetAdminAccount(admin ag_solanago.PublicKey) *RecenterPerpMarketAmm {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *RecenterPerpMarketAmm) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStateAccount sets the "state" account.
func (inst *RecenterPerpMarketAmm) SetStateAccount(state ag_solanago.PublicKey) *RecenterPerpMarketAmm {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(state)
	return inst
}

// GetStateAccount gets the "state" account.
func (inst *RecenterPerpMarketAmm) GetStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPerpMarketAccount sets the "perpMarket" account.
func (inst *RecenterPerpMarketAmm) SetPerpMarketAccount(perpMarket ag_solanago.PublicKey) *RecenterPerpMarketAmm {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(perpMarket).WRITE()
	return inst
}

// GetPerpMarketAccount gets the "perpMarket" account.
func (inst *RecenterPerpMarketAmm) GetPerpMarketAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst RecenterPerpMarketAmm) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RecenterPerpMarketAmm,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RecenterPerpMarketAmm) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RecenterPerpMarketAmm) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.PegMultiplier == nil {
			return errors.New("PegMultiplier parameter is not set")
		}
		if inst.SqrtK == nil {
			return errors.New("SqrtK parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.State is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.PerpMarket is not set")
		}
	}
	return nil
}

func (inst *RecenterPerpMarketAmm) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RecenterPerpMarketAmm")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("PegMultiplier", *inst.PegMultiplier))
						paramsBranch.Child(ag_format.Param("        SqrtK", *inst.SqrtK))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     admin", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     state", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("perpMarket", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj RecenterPerpMarketAmm) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `PegMultiplier` param:
	err = encoder.Encode(obj.PegMultiplier)
	if err != nil {
		return err
	}
	// Serialize `SqrtK` param:
	err = encoder.Encode(obj.SqrtK)
	if err != nil {
		return err
	}
	return nil
}
func (obj *RecenterPerpMarketAmm) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `PegMultiplier`:
	err = decoder.Decode(&obj.PegMultiplier)
	if err != nil {
		return err
	}
	// Deserialize `SqrtK`:
	err = decoder.Decode(&obj.SqrtK)
	if err != nil {
		return err
	}
	return nil
}

// NewRecenterPerpMarketAmmInstruction declares a new RecenterPerpMarketAmm instruction with the provided parameters and accounts.
func NewRecenterPerpMarketAmmInstruction(
	// Parameters:
	pegMultiplier ag_binary.Uint128,
	sqrtK ag_binary.Uint128,
	// Accounts:
	admin ag_solanago.PublicKey,
	state ag_solanago.PublicKey,
	perpMarket ag_solanago.PublicKey) *RecenterPerpMarketAmm {
	return NewRecenterPerpMarketAmmInstructionBuilder().
		SetPegMultiplier(pegMultiplier).
		SetSqrtK(sqrtK).
		SetAdminAccount(admin).
		SetStateAccount(state).
		SetPerpMarketAccount(perpMarket)
}
