// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package drift

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateSpotFeeStructure is the `updateSpotFeeStructure` instruction.
type UpdateSpotFeeStructure struct {
	FeeStructure *FeeStructure

	// [0] = [SIGNER] admin
	//
	// [1] = [WRITE] state
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateSpotFeeStructureInstructionBuilder creates a new `UpdateSpotFeeStructure` instruction builder.
func NewUpdateSpotFeeStructureInstructionBuilder() *UpdateSpotFeeStructure {
	nd := &UpdateSpotFeeStructure{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetFeeStructure sets the "feeStructure" parameter.
func (inst *UpdateSpotFeeStructure) SetFeeStructure(feeStructure FeeStructure) *UpdateSpotFeeStructure {
	inst.FeeStructure = &feeStructure
	return inst
}

// SetAdminAccount sets the "admin" account.
func (inst *UpdateSpotFeeStructure) SetAdminAccount(admin ag_solanago.PublicKey) *UpdateSpotFeeStructure {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *UpdateSpotFeeStructure) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStateAccount sets the "state" account.
func (inst *UpdateSpotFeeStructure) SetStateAccount(state ag_solanago.PublicKey) *UpdateSpotFeeStructure {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(state).WRITE()
	return inst
}

// GetStateAccount gets the "state" account.
func (inst *UpdateSpotFeeStructure) GetStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst UpdateSpotFeeStructure) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateSpotFeeStructure,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateSpotFeeStructure) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateSpotFeeStructure) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.FeeStructure == nil {
			return errors.New("FeeStructure parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.State is not set")
		}
	}
	return nil
}

func (inst *UpdateSpotFeeStructure) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateSpotFeeStructure")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("FeeStructure", *inst.FeeStructure))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("admin", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("state", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj UpdateSpotFeeStructure) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `FeeStructure` param:
	err = encoder.Encode(obj.FeeStructure)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UpdateSpotFeeStructure) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `FeeStructure`:
	err = decoder.Decode(&obj.FeeStructure)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdateSpotFeeStructureInstruction declares a new UpdateSpotFeeStructure instruction with the provided parameters and accounts.
func NewUpdateSpotFeeStructureInstruction(
	// Parameters:
	feeStructure FeeStructure,
	// Accounts:
	admin ag_solanago.PublicKey,
	state ag_solanago.PublicKey) *UpdateSpotFeeStructure {
	return NewUpdateSpotFeeStructureInstructionBuilder().
		SetFeeStructure(feeStructure).
		SetAdminAccount(admin).
		SetStateAccount(state)
}
