// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package drift

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdatePerpMarketMaxSlippageRatio is the `updatePerpMarketMaxSlippageRatio` instruction.
type UpdatePerpMarketMaxSlippageRatio struct {
	MaxSlippageRatio *uint16

	// [0] = [SIGNER] admin
	//
	// [1] = [] state
	//
	// [2] = [WRITE] perpMarket
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdatePerpMarketMaxSlippageRatioInstructionBuilder creates a new `UpdatePerpMarketMaxSlippageRatio` instruction builder.
func NewUpdatePerpMarketMaxSlippageRatioInstructionBuilder() *UpdatePerpMarketMaxSlippageRatio {
	nd := &UpdatePerpMarketMaxSlippageRatio{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetMaxSlippageRatio sets the "maxSlippageRatio" parameter.
func (inst *UpdatePerpMarketMaxSlippageRatio) SetMaxSlippageRatio(maxSlippageRatio uint16) *UpdatePerpMarketMaxSlippageRatio {
	inst.MaxSlippageRatio = &maxSlippageRatio
	return inst
}

// SetAdminAccount sets the "admin" account.
func (inst *UpdatePerpMarketMaxSlippageRatio) SetAdminAccount(admin ag_solanago.PublicKey) *UpdatePerpMarketMaxSlippageRatio {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *UpdatePerpMarketMaxSlippageRatio) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStateAccount sets the "state" account.
func (inst *UpdatePerpMarketMaxSlippageRatio) SetStateAccount(state ag_solanago.PublicKey) *UpdatePerpMarketMaxSlippageRatio {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(state)
	return inst
}

// GetStateAccount gets the "state" account.
func (inst *UpdatePerpMarketMaxSlippageRatio) GetStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPerpMarketAccount sets the "perpMarket" account.
func (inst *UpdatePerpMarketMaxSlippageRatio) SetPerpMarketAccount(perpMarket ag_solanago.PublicKey) *UpdatePerpMarketMaxSlippageRatio {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(perpMarket).WRITE()
	return inst
}

// GetPerpMarketAccount gets the "perpMarket" account.
func (inst *UpdatePerpMarketMaxSlippageRatio) GetPerpMarketAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst UpdatePerpMarketMaxSlippageRatio) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdatePerpMarketMaxSlippageRatio,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdatePerpMarketMaxSlippageRatio) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdatePerpMarketMaxSlippageRatio) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.MaxSlippageRatio == nil {
			return errors.New("MaxSlippageRatio parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.State is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.PerpMarket is not set")
		}
	}
	return nil
}

func (inst *UpdatePerpMarketMaxSlippageRatio) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdatePerpMarketMaxSlippageRatio")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("MaxSlippageRatio", *inst.MaxSlippageRatio))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     admin", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     state", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("perpMarket", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj UpdatePerpMarketMaxSlippageRatio) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `MaxSlippageRatio` param:
	err = encoder.Encode(obj.MaxSlippageRatio)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UpdatePerpMarketMaxSlippageRatio) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `MaxSlippageRatio`:
	err = decoder.Decode(&obj.MaxSlippageRatio)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdatePerpMarketMaxSlippageRatioInstruction declares a new UpdatePerpMarketMaxSlippageRatio instruction with the provided parameters and accounts.
func NewUpdatePerpMarketMaxSlippageRatioInstruction(
	// Parameters:
	maxSlippageRatio uint16,
	// Accounts:
	admin ag_solanago.PublicKey,
	state ag_solanago.PublicKey,
	perpMarket ag_solanago.PublicKey) *UpdatePerpMarketMaxSlippageRatio {
	return NewUpdatePerpMarketMaxSlippageRatioInstructionBuilder().
		SetMaxSlippageRatio(maxSlippageRatio).
		SetAdminAccount(admin).
		SetStateAccount(state).
		SetPerpMarketAccount(perpMarket)
}
